### ISSUE TITLE
Throws "Timeout"

### ISSUE THREAD

**Issue by xiufengliu** [discoproject/disco#101]
Hi, I am using 4 Map-Reduce to load the data (10G), but it always throws "Timeout" after loading for a while.  I have tried to set the parameters of results = job.wait('loaddim', True, 5) by refering the tuitorial on your disco 0.2.4 document, but it seems that "wait(name, [...])" is incorrect. 

Could you investigate it ? thanks!

xiliu@h54:~/workspace/etlonmapred/offline2/pygrametl> python paralleletl.py
['disco://localhost/TestResults_10G.csv', 'disco://localhost/TestResults_10G.csv', 'disco://localhost/TestResults_10G.csv', 'disco://localhost/TestResults_10G.csv']
Traceback (most recent call last):
  File "paralleletl.py", line 361, in <module>
    main()
  File "paralleletl.py", line 293, in main
    results = load_dims(srcurls, required_modules, name='dim', host=master, nr_maps=nr_map, nr_reduces=nr_reduce, profile=False)
  File "paralleletl.py", line 152, in load_dims
    results = job.wait()
  File "/home/xiliu/disco/pydisco/disco/core.py", line 170, in wait
    return self.check_results(name, start_time, poll_interval \* 1000)
  File "/home/xiliu/disco/pydisco/disco/core.py", line 161, in check_results
    raise JobError("Timeout", self.host, name)
disco.error.JobError: Job http://localhost:8989/dim@4f2:58ca9:e583c failed: Timeout
xiliu@h54:~/workspace/etlonmapred/offline2/pygrametl>

**Comment by xiufengliu** [comment]
Hi, I have found the solution! pls close this issue

**Comment by tuulos** [comment]
This is probably the same bug as #96 which was fixed by the commit a8c402929021e4

**Comment by tuulos** [comment]
fixed
