### ISSUE TITLE
pydisco cant run under python 2.4.3

### ISSUE THREAD

**Issue by mpechner** [discoproject/disco#106]
core.py has a
 try:
expect:
finally which is not allowed in 2.4. 

try:
  try:
  except:
finally:

**Comment by tuulos** [comment]
Support for Python 2.4 was dropped in 0.2.4. Even the most conservative linux distributions (Debian stable) have Python 2.5 now. The latest stable version of Python is already 2.6, so the extra trouble needed to support 2.4 did not make sense anymore.

**Comment by mpechner** [comment]
So you have discarded anyone using centos?  At least in the US it is considered a major commercial distro? Meaning the number of production systems running it. It is at Python 2.4.3 as is Red Hat. 

And yes it sucks. I do have to keep my code compatible with 2.4 even though my windows users are on 2.5 or 2.6.

Then please update your documentation. And give a good thumbs down to Red hat and Centos commercial users.  http://discoproject.org/doc/start/install.html

**Comment by mpechner** [comment]
I guess disco really is dead.

**Comment by tuulos** [comment]
what makes you think so?

**Comment by mpechner** [comment]
I did something else where I say this comment from march.  I still think if you looked at the number of centos and red hat, not fedora, deployments you would see that centos 5.5 which runs python 2.4.3 has more system deployed  in production than your other distros. python 2.4 is still something to support until  red hat and centos  ship version 6 and ti starts begin widely adopted.

In the meanwhile I am starting to learn rabbitMQ which does have python clients that run on centos 5.5.
