### ISSUE TITLE
purge_job fails and disco master crashes

### ISSUE THREAD

**Issue by jflatow** [discoproject/disco#109]
not sure yet exactly whats the cause but discodex queries occassionally give the following error, after which the disco master is completely dead:

Got Unable to access resource (http://localhost:8989/disco/ctrl/purge_job): Downloading http://localhost:8989/disco/ctrl/purge_job failed after 10 attempts: [Errno 61] Connection refused, make sure disco master is running at http://localhost:8989

**Comment by davin** [comment]
Perhaps you can try increasing polling_interval.  At least for issue #115, it seems to fix some mysterious problems.

**Comment by tuulos** [comment]
purge is totally refactored in 0.3, thanks to the new garbage collector

pls reopen the issue if the problem persists
