### ISSUE TITLE
combiner called many times with done=True

### ISSUE THREAD

**Issue by jseppanen** [discoproject/disco#118]
i have a combiner that writes OOB results when done=True. i'm seeing the combiner function being called 20 times with done=True.

here's my combiner code:

def train_combine(k, v, x, done, params):
    if done:
        put('norm@%d'%this_partition(), cPickle.dumps(params.norms, -1))
        put('err@%d'%this_partition(), cPickle.dumps(params.errs, -1))
    else:
        return [(k,v)]

Here's a snippet of the disco event log:

2010/03/04 09:53:00 disco-23 [map:994] Done: 434 entries mapped in total
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put norm@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/norm@994
2010/03/04 09:53:00 disco-23 [map:994] OOB put err@994 at disco-23/65/wsvd_2q@4f3:aa00b:63caa/oob/err@994
2010/03/04 09:53:00 disco-23 [map:994] Task finished in 0:00:05.400
2010/03/04 09:53:00 master Received results from map:994 @ disco-23.

**Comment by tuulos** [comment]
Each partition has a combiner of its own. When the map tasks finishes, all partitions are closed and their combiners are called respectively. That is why there are many calls to combiner with done = True.

Maybe confusingly this_partition() returns ID of the map task, not ID of the reduce partition in the map phase, as documented in

http://discoproject.org/doc/py/node/worker.html

This explains why all OOB calls have the same key above, although they belong to different (reduce) partitions.

Disco 0.2.3 didn't show the OOB messages in the event stream, so this behavior was not visible to the user although behind the scenes it did exactly the same thing.
