### ISSUE TITLE
master and worker conflicts with each other

### ISSUE THREAD

**Issue by hezila** [discoproject/disco#119]
When I start master and worker in the my lacal single machine, there are some problems:
when I first start master, I have problem for starting workers that it says:
# disco master start
# disco worker start

lighttpd -f /etc/disco/lighttpd-worker.conf already running

when first start worker, the problem is:
# disco worker start
# disco master start

lighttpd -f /etc/disco/lighttpd-master.conf already running

Please help me, thanks!

**Comment by tuulos** [comment]
If you use your master node as a worker, you don't need to run "disco worker start" there separately. "disco master start" takes care of both the roles.

**Comment by tuulos** [comment]
Works as intended.

**Comment by hezila** [comment]
thanx
