### ISSUE TITLE
bug error when I run the count_words.py

### ISSUE THREAD

**Issue by hezila** [discoproject/disco#122]
When I using the example in the set up tutorial. 
I configure my local machine as master, and running the count_words.py like this:
python count_word.py http://localhost:8989
I have configure the localhost node in the configuration page like this:
    Nodes   Max workers
    localhost   2

I have the follwing error log info:

2010/03/05 19:05:47master
ERROR: map:0 Task failed on all available nodes (or no nodes available). Aborting job.
2010/03/05 19:05:47master
map:0 added to waitlist
2010/03/05 19:05:47localhost
WARN: [map:0] Node failure: "Couldn't connect to localhost (timeout). Node blacklisted temporarily."
2010/03/05 19:05:15master
map:0 assigned to localhost
2010/03/05 19:05:15master
map:0 added to waitlist
2010/03/05 19:05:15master
Map phase
2010/03/05 19:05:15master
Starting job

**Comment by davin** [comment]
Perhaps try increasing the job status polling interval to 30 secs in count_words.py.  The default is 2.

.wait(poll_interval=30)

**Comment by davin** [comment]
What's your setup, e.g. os, platform, etc?  Are you behind a proxy?  Just curious if your error is related to issue #115, #123 or #104.

**Comment by hezila** [comment]
I have change the polling interval to 30, but it doesn't work.
thank you all the same.

**Comment by hezila** [comment]
My plateform is Archlinux, python 2.6.4
I'm not behind a proxy.
I think my problem is different from the issue #155, #123 or #104

**Comment by jflatow** [comment]
this is a configuration problem, not a bug in disco.
