### ISSUE TITLE
deb install broken by presence of Mono Web Service Discovery Tool 

### ISSUE THREAD

**Issue by mleyden** [discoproject/disco#124]
The latest deb install did not complete due to a /usr/bin/disco executable being already present. This is from the Mono project and is their Mono Web Service Discovery Tool.

Unpacking disco-master (from .../disco-master_0.2.4_all.deb) ...
dpkg: error processing /var/cache/apt/archives/disco-master_0.2.4_all.deb (--unpack):
 trying to overwrite '/usr/bin/disco', which is also in package mono-devel 0:2.4.2.3+dfsg-2
Processing triggers for ureadahead ...
Errors were encountered while processing:
 /var/cache/apt/archives/disco-master_0.2.4_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by jflatow** [comment]
You can use make install to install to /usr/local, wontfix name of disco
