### ISSUE TITLE
error with deb-packages: /etc/disco/disco.conf not found

### ISSUE THREAD

**Issue by tuulos** [discoproject/disco#13]
Error while trying out the experimental deb-packages on a fresh Deb 5 VM.  There is no /
etc/disco/disco.conf found anywhere. See

http://groups.google.com/group/disco-dev/browse_thread/thread/1ee969fb18aa61d3?hl=en

**Comment by johnpena** [comment]
Are there any workarounds for this problem? I've had the same issue.
