### ISSUE TITLE
builtin messages can exceed rate limit

### ISSUE THREAD

**Issue by jflatow** [discoproject/disco#139]
if a task proceeds too quickly the status events can overwhelm the master's rate limit.

**Comment by tuulos** [comment]
workaround: set status_interval=0 (or status_interval=1000000 or so)

eventually we could define a new internal non-rate-limited message type for handling situations like this

**Comment by tuulos** [comment]
duplicate #169

**Comment by tuulos** [comment]
#169 fixed
