### ISSUE TITLE
Add a note about proper hostname resolving in docs

### ISSUE THREAD

**Issue by tuulos** [discoproject/disco#140]
In an incident reported on #idiscoproject, Disco could not start slave nodes properly, always giving just timeout. The problem was traced down to the following /etc/hosts file:

127.0.0.1       localhost.localdomain localhost master
::1     localhost6.localdomain6 localhost6 master
172.25.25.1 worker1
172.25.25.2 worker2
172.25.25.3 worker3
172.25.25.4 master

which lists master as an alias for localhost. When master was removed from the first two lines, Disco started to work.

This problem could be properly documented and/or detected by Disco.

**Comment by jflatow** [comment]
also, can't use localhost if you have more than one node
