### ISSUE TITLE
Dynamic auto-balancing partition function

### ISSUE THREAD

**Issue by tuulos** [discoproject/disco#146]
1) a dynamic partition function that observer the key distribution on the fly, and spreads data accordingly

or 2) a system to first check the data distribution and then produce a good partition function accordingly

most often you just want equal keys to the same partition - system could optimize everything else behind the scenes

both 1) and 2) could warn you about an unbalanced distribution so you wouldn't have to wait until reduce to see that it's going to take ages

**Comment by jflatow** [comment]
duplicate #61
