### ISSUE TITLE
Redirected URL in step 6 on http://discoproject.org/doc/start/install.html

### ISSUE THREAD

**Issue by timcera** [discoproject/disco#160]
In step 6 on page http://discoproject.org/doc/start/install.html the URL used for input (http://discoproject.org/chekhov.txt) should be (http://discoproject.org/media/text/chekhov.txt).  It redirects fine in a browser but disco just throws a 301 error - at least on my system.

After fixing above - works great!

**Comment by tuulos** [comment]
fixed
