### ISSUE TITLE
Random bytes in a message can make json encoding fail in event_server

### ISSUE THREAD

**Issue by tuulos** [discoproject/disco#161]
If a message output to stdout contains random bytes, the worker may fail with

Worked died unexpectedly: {ucs,{bad_utf8_character_code}}

**Comment by pmundkur** [comment]
the error is thrown from within xmerl_ucs:from_utf8.  the helper function from_utf8 uses is useful, but not exported from the module.  from_utf8 does an exit on invalid input, with no possibility of retrieving the partially decoded result.  we could modify mochijson2 to do a catch around its calls to xmerl_ucs:from_utf8, or copy the xmerl_ucs:expand_utf8 helper function.

**Comment by tuulos** [comment]
Closed by 3c4d4a6d4
