### ISSUE TITLE
Add DiscodexClient.wait method to block until Discodex index or metaindex job finishes

### ISSUE THREAD

**Issue by sqs** [discoproject/disco#180]
This is implemented by having Discodex.wait (the new method) call Disco.wait.

sqs/disco@95f226de7511b3d03ff76dfcb8dced22bd15d8a3
#### Potential objections
1. DiscodexClient methods are generally 1-to-1 mapped to methods on the REST API. This is slightly unclean, then, since `wait` isn't a method on the server. A cleaner solution would be to make DiscodexClient.index and .metaindex return a Job-like class with this `wait` method.
2. This introduces a dependency on Disco in Discodex. The host that calls Discodex.wait must have access to the Disco master, not just the Discodex HTTP server.
3. Discodex didn't have any tests, but I created one using the same style as the Disco tests. I didn't update any Makefiles yet to include this test. Is anybody working on a Discodex test suite?

**Comment by jflatow** [comment]
The DISCO_HOST is a setting for the server, not for the client, so there is no guarantee for the client that the master is the same, or even that the client can reach the master. If you happen to know where the disco master is, you can use the Disco.wait method with the index/job name.

**Comment by sqs** [comment]
OK, got it. Then this is certainly not worth adding.

Maybe somebody somewhere would like to monitor discodex job status without knowing the disco master host, but that'd require additions to the django www code also and isn't really useful for most people. So, I'll close this.
