### ISSUE TITLE
encode_netstring_str is broken preventing DDFS tags from being used as inputs

### ISSUE THREAD

**Issue by jessekempf** [discoproject/disco#185]
encode_netstring_str() can't handle any octets > 0x7F. This makes it impossible to use DDFS -- a UnicodeDecodeError is thrown and the job explodes as described here: http://groups.google.com/group/disco-dev/browse_thread/thread/bd735e931e0b7956

I rewrote encode_netstring_str() so that it can handle octets > 0x7F.

See http://github.com/jessekempf/disco/commit/9fe5d95990e7e9af0a7e53235889b0221b9e2374 for the patch.

**Comment by tuulos** [comment]
fixed by 279f28
