### ISSUE TITLE
ddfs cat can hang even if just one of the replicas is not available

### ISSUE THREAD

**Issue by tmielika** [discoproject/disco#223]
The command

ddfs cat tag://ddfstag

hangs if the first replica is not accessible, whereas e.g. wget immediately gives 'no route to host' which is superior w.r.t. UX.

**Comment by pooya** [comment]
This is fixed with commit 9918000c5ab1fe2fa3970c86bd4ac176e5064046. The ddfs xcat command still waits a long time for unavailable replicas.
