### ISSUE TITLE
expose task/worker related settings in ui

### ISSUE THREAD

**Issue by pmundkur** [discoproject/disco#230]
currently settings like DISCO_SORT_BUFFER_SIZE, DISCO_WORKER_MAX_MEM can be only changed with a disco restart.  it might be worth supporting dynamically changing them using the ui

**Comment by pmundkur** [comment]
15:43 @tuulos mundkur, what it comes to settings, now with new worker changes it makes sense to distinguish between settings specific to one worker vs. those that apply to all of them
15:44 @tuulos DISCO_WORKER_MAX_MEM and DISCO_SORT_BUFFER_SIZE might not be implemented, say, by an ocaml worker

**Comment by jflatow** [comment]
these can anyway be controlled by the user when they submit the job
