### ISSUE TITLE
problem running count_words.py on osx

### ISSUE THREAD

**Issue by gpciceri** [discoproject/disco#236]
I'm trying the standard count_words.py sample.
Between map (done, successful) an reduce (waiting) I take

WARN: Creating index file failed at localhost: {badrpc,
                                                {'EXIT',
                                                 {{badmatch,{error,badarg}},
                                                  [{ddfs_util,concatenate,2},
                                                   {shuffle,process_url,3},
                                                   {shuffle,
                                                    '-process_task/3-lc$^0/1-0-',
                                                    3},
                                                   {shuffle,
                                                    '-merged_index/3-fun-0-',
                                                    4},
                                                   {lists,foldl,3},
                                                   {shuffle,merged_index,3},
                                                   {shuffle,
                                                    combine_tasks_node,4},
                                                   {rpc,
                                                    '-handle_call_call/6-fun-0-',
                                                    5}]}}} (retrying

Any idea?
Best regards
/gp

**Comment by ghost** [comment]
The same problem with fresh installation of recent version (1b6b264) on OS X 10.6.6

**Comment by pmundkur** [comment]
duplicate #236

**Comment by alexcepoi** [comment]
this is closed as a duplicate of itself?

**Comment by pooya** [comment]
@alexcepoi That seems to be a mistake. Is this still a bug (I haven't seen it)?

**Comment by alexcepoi** [comment]
I'm running an old version from dec 2012 and I do get that, although not sure if it has been fixed since then. Will update when I upgrade :)
