### ISSUE TITLE
process_url error

### ISSUE THREAD

**Issue by tyrionlin** [discoproject/disco#239]
My Disco was running on one server。 When I run “python example/util/count_word.py",erlang throw exception in process_url.  I found there is a bug in process_url/1：
process_url([Id, <<"part://", _/binary>> = Url],
            DataRoot,
            {PartPath, PartUrl}) ->
    PartFile = ["part-", Id],
    PartSrc = [DataRoot, "/", disco:disco_url_path(Url)],
    PartDst = [PartPath, "/", PartFile],
Id = << 0 >> in my example,I think it should be PartFile ["part-", binary_to_list(Id)],else error will throw in  prim_file:open(Dst,...

**Comment by pmundkur** [comment]
fixed in current master
