### ISSUE TITLE
POST to ddfs doesn't work with httplib; pycurl required

### ISSUE THREAD

**Issue by rmalouf** [discoproject/disco#241]
Trying to run the count_words.py example without pycurl installed lead to UnicodeDecodeErrors. the problem seems to be that comm.py POSTs the data to ddfs using Python's httplib, which is (I think?)  incapable of dealing with binary data.  The solution for me was easy -- I installed pycurl and things worked fine. I guess you could just require pycurl and call this a documentation error...

**Comment by jflatow** [comment]
this sounds like a json issue; what version of python/json library are you using?

**Comment by pmundkur** [comment]
This seems to be a known issue with Python: http://bugs.python.org/issue11898

**Comment by pmundkur** [comment]
Added to docs for 0.4.4.
