### ISSUE TITLE
DISCODEX_HOME needs documentation

### ISSUE THREAD

**Issue by JensRantil** [discoproject/disco#246]
In the [installation guide for discodex](http://discoproject.org/doc/contrib/discodex/tutorial.html#installation) there is no mention of <code>DISCODEX_HOME</code> even though it is mentioned when starting discodex the first time:
<code>jens@supraflex:~/src/disco$ discodex start
DISCODEX_HOME is not specified, where should Discodex live?</code>
Should it point to the Django home installation, or to where the discodex data should be stored? Can it point to the same data directory as disco?

To further improve this you might consider even adding it as a default path in the <code>/etc/disco/settings.py</code> template to make things easier to get started with discodex.

**Comment by jflatow** [comment]
Jens: http://discoproject.org/doc/contrib/discodex/api/discodex/settings.html

If you want to do a system install you need to pick a place where discodex should create its directories (for logging/pid etc.)
