### ISSUE TITLE
Output from command-line examples

### ISSUE THREAD

**Issue by JensRantil** [discoproject/disco#247]
I am a new user to disco. While I am mostly happy with the documentation provided, it would be wonderful if the output from the command-line examples also could be provided. Sometimes you, as a reader, don't really know what to expect as output.

For example, in [the discodex installation tutorial](http://discoproject.org/doc/contrib/discodex/tutorial.html#installation), you provide the example <code>discodex list</code>. However, as a reader/newcomer, you really have no idea what kind of output will be printed thereafter.

**Comment by pooya** [comment]
I think this issue no longer applies. Please re-open if you think otherwise.
