### ISSUE TITLE
install-discodex target does not install binary

### ISSUE THREAD

**Issue by JensRantil** [discoproject/disco#248]
<code>make install-discodex</code> does not install the discodex command-line utility. While it is documented how to do this in <code>contrib/discodex/INSTALL</code>, it should either be mentioned to this in [the installation guide](http://discoproject.org/doc/contrib/discodex/tutorial.html#installation), be added to the <code>setup.py</code> for discodex (which is invoked by <code>make install-discodex</code>?) or be added in the root Makefile for the <code>install-discodex</code> target.

**Comment by Zhenia-121** [comment]
Tell me please, this problem was solved?

**Comment by JensRantil** [comment]
@Zhenia-121 I searched https://github.com/discoproject/disco/blob/master/Makefile and https://github.com/discoproject/discodex/blob/master/Makefile after "install-discodex". Couldn't find any reference.

discodex is [no longer part of disco](https://disco.readthedocs.org/en/latest/releases.html?highlight=discodex#id10) and I'm not sure it has a separate documentation or not. I believe not. I'm closing this issue. Please reopen it [here](https://github.com/discoproject/discodex/issues/new) if this is still an issue.
