### ISSUE TITLE
comm module doesn't handle HTTP responses without content-length correctly

### ISSUE THREAD

**Issue by tuulos** [discoproject/disco#252]
comm module doesn't work correctly when requesting data from a HTTP server that doesn't support range requests or which doesn't return a content-length header in response.

A solution could be to fall back to normal non-chunked (non-range) requests if ranges/content-length are not supported.

**Comment by srobertson** [comment]
dangra's patch did the trick for me

**Comment by dangra** [comment]
fixed by https://github.com/discoproject/disco/commit/6de939b

**Comment by dangra** [comment]
this issue can be closed.

**Comment by pooya** [comment]
Thanks.
