### ISSUE TITLE
Failure in "Moving results to resultfs" is a fatal error

### ISSUE THREAD

**Issue by tuulos** [discoproject/disco#26]
If Glusterfs fails on a single node, it is detected only when results are being moved to resultfs, which leads to a fatal error. However, the error should be recoverable by executing the task on another node.

**Comment by tuulos** [comment]
We should move the whole resultfs logic from garbage_collect:move_results() to the client side.

**Comment by jflatow** [comment]
gluster is gone in disco 0.3, use ddfs
