### ISSUE TITLE
Discodex exits with [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rspeer** [discoproject/disco#262]
I installed Discodex using "python setup.py install" and symlinking the binary, and I made a directory called /srv/discodex and set that as DISCODEX_HOME. When I try to run "discodex start", I get:
[Errno 2] No such file or directory

I'm not sure what code is outputting this error.

Is there perhaps supposed to be something _in_ DISCODEX_HOME? What should go there?

**Comment by rspeer** [comment]
Okay, I took a guess and it worked. It wanted DISCODEX_HOME to be the discodex/contrib directory that I installed from.

This is strange, then: it seems that Discodex wants to be installed _and_ running out of a Git repository. Is there any way to actually install Discodex systemwide and run it as a startup daemon?

**Comment by jflatow** [comment]
You can just use a symlink to the source directory.
