### ISSUE TITLE
init.d script fails

### ISSUE THREAD

**Issue by JensRantil** [discoproject/disco#263]
Hi,

I used to have the previous Debian package version of 0.3.2 installed on my Ubuntu 10.04 box. I later upgraded to version 0.4.0. Since then
`$ sudo /etc/init.d/disco-master start`
fails with the message
`* Starting disco master  disco-master                                                                                                                                      [Errno 13] Permission denied: '/var/run/disco/'`
The error can be corrected by issuing
`$ sudo mkdir /var/run/disco`
`$ sudo chown disco:disco /var/run/disco`
````$ sudo /etc/init.d/disco-master start
- Starting disco master  disco-master                                                                                                                                      Master jens-desktop:8989 started````

**Comment by tuulos** [comment]
The directory is created by the package manager when you install disco-master. However, in Ubuntu (in contrast to Debian), /var/run gets cleared out on reboot:

"Using Ubuntu 8.10 server, /var/run and /var/log are mounted on a tempfs, which means they're cleared out on a reboot."
https://answers.launchpad.net/ubuntu/+question/56285

As a workaround, you can add

```
mkdir -p /var/run/disco
chown disco:disco /var/run/disco
```

 in the beginning of the /etc/init.d/disco-master script.

**Comment by JensRantil** [comment]
I tried looking for the init.d script in the discoproject repository. Is it there? Or somehow generated?

**Comment by JensRantil** [comment]
Found [it](https://github.com/discoproject/disco/blob/master/pkg/debian/disco-master.init). Can't find any references to /var/run/disco, though. Is this a fix that needs to be put into Erlang code?

**Comment by tuulos** [comment]
/var/run/disco is created by the package manager (apt) based on [disco-master.dirs](https://github.com/discoproject/disco/blob/master/pkg/debian/disco-master.dirs)

The workaround I mentioned above should be added to /etc/init.d/disco-master after you have installed the disco-master package.

**Comment by jflatow** [comment]
This should be fixed in the current HEAD and upcoming release (0.4.2). If not, please re-open.
