### ISSUE TITLE
client proxy (DISCO_PROXY) is broken

### ISSUE THREAD

**Issue by jflatow** [discoproject/disco#269]

**Comment by pmundkur** [comment]
Should be fixed in 0.4.2

**Comment by srobertson** [comment]
Disco  0.4.2 seems to ignore disco proxy for ddfs xcat

**Comment by pmundkur** [comment]
Could you try this fix: https://github.com/discoproject/disco/commit/732cabd4c298d9819b0635db8778ae4a330bc0a3

**Comment by srobertson** [comment]
That probably helped but I also had to make this change

https://github.com/srobertson/disco-client/commit/fe5ac05b42f99584eab3d03e837c5272b5e84219

I'm actually trying to mimic xcat with this code:

  from disco.func import chain_reader
    results = {}  
    for conn in self.ddfs.pull(tag):
      for key,val in chain_reader(conn,len(conn),conn.url):
        results[key] = val
    return results

so I can use it programmatically, as I don't see a call in disco.ddfs that does that for me.

**Comment by pmundkur** [comment]
It looks like client proxy mode still needs some fixes.

**Comment by pmundkur** [comment]
srobertson, does this help?  https://github.com/pmundkur/disco/commit/3bf5e5f8b4ca97c4cec6f4df911ffea8c81f024e

**Comment by pmundkur** [comment]
Should be fixed (hopefully) in 0.4.3.
