### ISSUE TITLE
Debian package init.d script is broken 

### ISSUE THREAD

**Issue by lukehoersten** [discoproject/disco#277]
The Debian package (as hosted in the `deb http://discoproject.org/debian` repo) is broken. The `init.d` script doesn't create the `/var/run/disco/` directory which disco-master depends on to start. For example:

```
$ sudo /etc/init.d/disco-master start
 * Starting disco master  disco-master
[Errno 13] Permission denied: '/var/run/disco/'
```

Simply creating the mentioned directory and chowning to disco:disco fixes it.

**Comment by jflatow** [comment]
This shouldn't happen if you are using apt-get.

**Comment by lukehoersten** [comment]
I did use apt-get.
