### ISSUE TITLE
Disco CLI tool needs a version

### ISSUE THREAD

**Issue by lukehoersten** [discoproject/disco#283]
We're having a hard time administering clients because the `disco` CLI tool doesn't have a `--version`-like option.

**Comment by cmorgan** [comment]
+1, it is very difficult to gauge the success of an upgrade without a version string. I have found that versioning through git i.e. "git describe --tags" is very useful. 

In the case of Disco we would want to interrogate both the Python bindings and also the core Erlang code for a version string as both may be updated independently.

**Comment by pmundkur** [comment]
Added for 0.4.4
