### ISSUE TITLE
DISCO_GC_AFTER doesn't work

### ISSUE THREAD

**Issue by lukehoersten** [discoproject/disco#284]
`DISCO_GC_AFTER = 1 * 60 * 60` in `settings.py` should GC the job homes older than one hour if I understand correctly yet this doesn't happen -- job homes were left untouched. Nothing abnormal in the master logs. Please let me know if I can help to collect more debug data.

**Comment by lukehoersten** [comment]
Actually I think the web GUI's `[delete all job data]` link doesn't actually delete the job home either. It just clears out the web GUI. Not sure if this is intended behavior.

**Comment by jflatow** [comment]
This should be fixed in the current HEAD and upcoming release (0.4.2). If not, please re-open.

**Comment by lukehoersten** [comment]
We'll update and let you know. Thanks Jared.

**Comment by pazooki** [comment]
What's the status for this bug? is it fixed on "Disco 0.4.3-34" ?

Thanks.
