### ISSUE TITLE
Can't run job when creating new one by inherit Job

### ISSUE THREAD

**Issue by marw** [discoproject/disco#287]
I tried to write job by inherit disco.job.Job

I modified examples/faq/chain.py from disco 4.1 distribution:

``` python
from disco.job import Job
class FirstJob(Job):
    input = ["file://testwords.txt"]
    @staticmethod
    def map(line, params):
        yield int(line) + 1, ""
if __name__ == "__main__":
    last = FirstJob().run().wait()
```

In same folder I created file "testwords.txt" and run mychain.py, I got:
disco.error.JobError: Job FirstJob@529:f4221:5146f failed: Status dead
in disco interface:
AttributeError: 'module' object has no attribute 'FirstJob'

It look like invalid JobPack creation, I expect that disco pack file with class.

Similar problem when running http://discoproject.org/doc/howto/discodb.html#discodb-tutorial

**Comment by ghost** [comment]
We are facing the same problem when running the examples/faq/chain.py, we are using Disco 0.4.1

**Comment by aidenbell** [comment]
Ran into this on Disco 0.4.1-155-g2d7b154

**Comment by ghost** [comment]
Hi Aiden,
Any solution to the issue? Any pointers greatly appreciated.
Thanks
Sharsch

On Apr 19, 2012, at 5:02 PM, Aiden Bell
reply@reply.github.com
wrote:

**Comment by aidenbell** [comment]
No solution yet. At a rough guess it will be the pickling of the Job.

**Comment by ghost** [comment]
what you mean by pickling of the job? I am just running the example
given in examples/faq/chain.py

On Thu, Apr 19, 2012 at 6:40 PM, Aiden Bell
reply@reply.github.com
wrote:

**Comment by fernandolfs** [comment]
any solution?

**Comment by pmundkur** [comment]
See http://groups.google.com/group/disco-dev/browse_thread/thread/c828b4b88c7b6fcb

**Comment by pmundkur** [comment]
Added to docs for 0.4.4.
