### ISSUE TITLE
disco using foo instead of foo.local on macosx

### ISSUE THREAD

**Issue by adriaant** [discoproject/disco#29]
On macosx, disco-worker gets a master_url in sys.argv[4] that on macosx does not use localhost if you're using a single host but rather the name part of 'foo.local' (ie 'foo'), the alternative host naming scheme. Since this doesn't resolve disco fails with "WARN [map:0] Failed to get http://foo:7000/disco/master/_disco_4441/2c/wordcount@1251260554//params: (2, 'Temporary failure in name resolution')"

To fix I hack node/disco-worker with:
master_url = master_url.replace('foo', 'localhost')

**Comment by tuulos** [comment]
Thanks adriaant for reporting this bug! Actually we are already working on this issue with osx, so you can expect a fix soon.

**Comment by tuulos** [comment]
Fixed in 0.2.3
