### ISSUE TITLE
discodex clone command missing

### ISSUE THREAD

**Issue by spil-dave** [discoproject/disco#292]
Following the discodex tutorial, discodex running OK.

Enter command:

 discodex clone _discodex:discodb:@52e:db074:2e9b0   somesensiblename

Result:
  unrecognized command: clone _discodex:discodb:@52e:db074:2e9b0

discodex --help

Result:

discodex --help
Usage:
    discodex 
    discodex append <indexaspec> <indexbspec>
    discodex delete <indexspec>
    discodex get <indexspec>
    discodex help 
    discodex index [url ...]
    discodex items <indexspec>
    discodex keys <indexspec>
    discodex list 
    discodex metaquery <indexspec> [query]
    discodex put <indexspec> url ...
    discodex query <indexspec> [query]
    discodex restart 
    discodex start 
    discodex status 
    discodex stop 
    discodex values <indexspec>

No 'clone' command.  

Examined contrib/discodex/bin/discodexcli.py     The 'clone' command is missing.

**Comment by jflatow** [comment]
Docs should be updated, but use `ddfs cp` instead.
