### ISSUE TITLE
ddfs chunk data:bigtxt bigfile.txt -> Invalid tag (403)

### ISSUE THREAD

**Issue by Dieterbe** [discoproject/disco#293]
Hi, when I follow the tutorial @ http://discoproject.org/doc/start/tutorial.html
(using latest code from git)
I get the following error when trying to put bigfile.txt chunked on the DDFS, when running the command on the master node.

```
dplaetin@n-0:~/disco$ bin/ddfs chunk data:bigtxt bigfile.txt
Unable to access resource (http://n-0.map-reduce2.search.wall2.test:8989/ddfs/tag/bigfile.txt): Invalid tag (403)
```

FWIW (just to show the server can be connected to, on my network at least):

```

dplaetin@n-0:~/disco$ telnet n-0.map-reduce2.search.wall2.test 8989
Trying 10.2.1.97...
Connected to n144-20a.wall2.test.
Escape character is '^]'.
Host n-0.map-reduce2.search.wall2.test
GET / HTTP/1.1

Connection closed by foreign host.
```

thanks!

**Comment by Dieterbe** [comment]
though this works, so the issue comes down to: why the weird error about an invalid tag?

```
dplaetin@n-0:~/disco$ bin/ddfs chunk data:bigtxt ./bigfile.txt
created: disco://localhost/ddfs/vol0/blob/ad/bigfile_txt-0$530-1bcc5-203f7
```

This is sortof documented @ http://discoproject.org/doc/howto/chunk.html
but it's weird nonetheless.
According to:

```
$ bin/ddfs -h | grep chunk
    ddfs chunk tag [url ...]
```

only 1 tag can be specified anyway, so either update the above help message (and extend the help message to say "using the following tags") _or_ change the code to interpret the thing after the tag as file, without requiring `./` IMHO.

**Comment by pooya** [comment]
Commit 86987b89a1a57eff70ecea2d88d06aaf19905c44 adds a help message about this issue.  Thanks.
