### ISSUE TITLE
make it more explicit that jobdict.worker cannot be a filename in DDFS

### ISSUE THREAD

**Issue by Dieterbe** [discoproject/disco#295]
http://discoproject.org/doc/lib/worker/index.html#disco.worker.Worker.jobdict describes how to use a local file, or a tag in DDFS.
Maybe it would help to clarify that you cannot just specify a filename in DDFS directly

I can implement changes like these if you agree with me.

**Comment by jflatow** [comment]
Please submit a pull request!
