### ISSUE TITLE
user must set PYTHONPATH and invoke count_words.py in correct dir

### ISSUE THREAD

**Issue by Dieterbe** [discoproject/disco#296]
According to http://discoproject.org/doc/start/tutorial.html and also http://discoproject.org/doc/start/install.html the user can just run `python count_words.py` resp. `python examples/util/count_words.py`
However this won't work if PYTHONPATH is not set (no hint is made towards this on any of these pages) and also for the first page the path is not correct.
The correct invocation is something like:

```
export PYTHONPATH=./lib
python examples/util/count_words.py
```

**Comment by jflatow** [comment]
The assumption is that Disco is installed (which means especially that the Python library can be imported). How you do that is up to you (e.g. if you want to just use PYTHONPATH), but instructions are given about how to install the library elsewhere.
