### ISSUE TITLE
Failed to register the worker using IP Address

### ISSUE THREAD

**Issue by amryamanah** [discoproject/disco#303]
Hi .. 

Today me and my colleagues try to use disco in our environment, but its seems that disco dns resolver cant accept ip address .
in example 
   we can register a worker for http://localhost but we cant register http://127.0.0.1

is that any fixed or workaround for this problem?

**Comment by pmundkur** [comment]
This is a problem with Erlang, unfortunately.  Is there any reason you cannot use DNS?

**Comment by amryamanah** [comment]
i see, because we plan to use it in dynamic environment, so its just not that efficient if we need to deploy new dns server and cnfigure it to register that dynamic machine dns, because they will be destroyed anyway after process done :(. But thanks anyway, at least its known problem.
