### ISSUE TITLE
docs specify too-low minimum erlang version

### ISSUE THREAD

**Issue by danohu** [discoproject/disco#308]
I believe the minimum erlang version in the docs is too low.

http://discoproject.org/doc/start/install.html
specifies "Erlang/OTP R13B or newer"

However, attempting to build HEAD (2d7b154cf7244447b87c3d2585968d93212ac555) with Erlang R13B03 (erts-5.7.4) gave the following error:

$ cd DISCO_HOME
$ make
cd master && ./rebar     get-deps && ./rebar     compile
Uncaught error in rebar_core: {'EXIT',{{badmatch,{error,badfile}},
                                       [{rebar_core,select_modules,3},
                                        {rebar_core,acc_modules,4},
                                        {rebar_core,process_dir0,6},
                                        {rebar_core,process_commands,2},
                                        {rebar,main,1},
                                        {escript,run,2},
                                        {escript,start,1},
                                        {init,start_it,1}]}}
make: **\* [master] Error 1

upgrading erlang to R14B02 (erts-5.8.3) fixed the error.
This seems to have changed between 4.0.1 and 2d7b154cf7244447b87c3d2585968d93212ac555. i.e. 4.0.1 builds correctly with erlang R13B03.

**Comment by pmundkur** [comment]
Docs have been updated to say erlang 14A (available on debian stable/squeeze) is now the min supported version.  Thanks for the report!

**Comment by xhancar** [comment]
Really updated? There is "Erlang/OTP R13B or newer" on http://discoproject.org/doc/start/install.html#prerequisites

**Comment by pmundkur** [comment]
The website will reflect the docs once 0.4.2 is released.

**Comment by hussainbohra** [comment]
Today I started my another set-up in Ubuntu 12.04 and am getting this error. I have verified my Erlang version it is 15B01

Please have a look in the following details:

drwxrwxr-x  2 ubuntu ubuntu 4096 Aug 18 08:39 util/
ubuntu@ubuntu-VirtualBox:~/bigdata/disco$ make
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{crypto,start,[],[]},
                                 {rebar,run_aux,1,[]},
                                 {rebar,main,1,[]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,727}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,277}]},
                                 {init,start_it,1,[]},
                                 {init,start_em,1,[]}]}}
make: **\* [dep] Error 1
ubuntu@ubuntu-VirtualBox:~/bigdata/disco$ erl
Erlang R15B01 (erts-5.9.1) [source] [async-threads:0] [kernel-poll:false]

Eshell V5.9.1  (abort with ^G)

Any pointer will be highly appreciated.
