### ISSUE TITLE
ebin directory-location problems when upgrading existing install

### ISSUE THREAD

**Issue by danohu** [discoproject/disco#309]
Where there is an existing disco installation, "make install" puts ebin in a subdirectory of its usual location

[install once, to simulate a prior install]
$ cd DISCO_HOME
$ make
$ sudo make install
$ sudo make clean

ebin is installed to:
/usr/local/lib/disco/master/ebin

[re-install, exposing the bug]
$ make
$ sudo make install

ebin is installed to:
/usr/local/lib/disco/master/ebin/ebin

Consequently, disco will pick up the code from the earlier install, rather than the current one.

I suspect this is a side-effect of recent changes to the Makefile, e.g. 79e4e6259c2027afa4dd889f422a2b63f99b947d

[I also encountered a similar problem with the www directory, but have been unable to reproduce that]

All this using current head (2d7b154cf7244447b87c3d2585968d93212ac555). Happened both over an existing 4.0.1 install, and replicating the problem by installing head twice in succession.

**Comment by danohu** [comment]
on the other hand: running "sudo make uninstall" before "sudo make install" avoids this issue. Is that the preferred way of handling upgrades?

**Comment by pmundkur** [comment]
Repeated 'make install's should now work.  Thanks for the report!
