### ISSUE TITLE
Lack of logging for long tag error

### ISSUE THREAD

**Issue by aidenbell** [discoproject/disco#314]
Long tags cause an underlying "File name too long" error, whereas Disco only provides, for example

disco.error.CommError: Unable to access resource( <long tag here> ):
Internal server error: replication_failed (500)

To clients when creating tags that exceed the OS filename maximum for that filesystem. The console output in nodaemon mode reports no issues or debugging information.

We experienced this with a 317-character tag on Linux ext4 ... but other limits apply depending on OS/Filesystem.

**Comment by aidenbell** [comment]
Web UI reports: Disco 0.4.1-155-g2d7b154 
Git: 2d7b154cf7244447b87c3d2585968d93212ac555

**Comment by pmundkur** [comment]
This should be fixed in 0.4.2.  Please reopen if not.
