### ISSUE TITLE
/var/log/disco/*.log needs logrotate

### ISSUE THREAD

**Issue by tubaman** [discoproject/disco#319]
The log file in /var/log/disco grows without bound and needs to be rotated.  I'm using the 0.4.1 debian packages.  Would it be possible to include a logrotate snippet as part of the debian packaging?  Here's an logrotate example from ejabberd(also written in erlang):

```
/var/log/ejabberd/ejabberd.log {
    weekly
    missingok
    rotate 12
    size 1M
    compress
    delaycompress
    ifempty
    create 640 ejabberd adm
    postrotate
        /usr/sbin/ejabberdctl reopen-log > /dev/null
    endscript
}
```

I'd like to submit a patch for this.  What command should I run to reopen the log after rotating? (see ejabberdctl above)

**Comment by tubaman** [comment]
It looks like lager detects a rotated log and reopens automatically.
http://basho.com/blog/technical/2011/07/20/Introducing-Lager-A-New-Logging-Framework-for-ErlangOTP/

**Comment by pmundkur** [comment]
In 0.4.1, you can use http://discoproject.org/doc/disco/lib/settings.html#envvar-DISCO_ROTATE_LOG
Set this to true in your master:/etc/disco/settings.py.    This will however only rotate logs on startup.

0.4.2 uses lager, and so implements log-rotate based on size/time.  The log-rotate parameters are currently hard-coded in lib/cli.py:basic_args(), but should be exposed in settings.   You could submit a patch for this if you wish: expose the parameters with user-friendly names in settings.py, and use them in cli.py.

**Comment by tubaman** [comment]
DISCO_LOG_ROTATE just rotates logs on startup according to the docs[1].
If disco runs continuously the log grows without bound.  I've just
submitted a pull request[2] that includes a logrotate config file that
builds with the debian package.  It seems to be correctly rotating logs
in my cluster.
1. http://discoproject.org/doc/disco/lib/settings.html#envvar-DISCO_ROTATE_LOG
2. https://github.com/discoproject/disco/pull/320

**Comment by pmundkur** [comment]
Tubaman, I'm not sure we could pull this, since the latest master is now using lager, which does logrotate.

**Comment by tubaman** [comment]
On Fri, May 18, 2012 at 05:34:46PM -0700, Prashanth Mundkur wrote:

> Tubaman, I'm not sure we could pull this, since the latest master is now using lager, which does logrotate.

I totally understand.  I will say this.  Debian recommends[1] that
log rotation be done by logrotate.  Lager supports[2] either external
rotation with a tool like logrotate or internal rotation.  I agree that
the lager settings should be exposed via settings.py.  That way the user
can choose to centrally administer their rotation policies or let lager
handle it for them.  If I have time, I'll try to create a patch.

Thanks!
1. http://www.debian.org/doc/debian-policy/ch-files.html#s10.8
2. https://github.com/basho/lager/blob/master/README.org

**Comment by pmundkur** [comment]
Closing.  Separate patch to expose lager in settings happily accepted.
