### ISSUE TITLE
Disco 0.2.3 master can't connect to remote Amazon EC2 nodes

### ISSUE THREAD

**Issue by cpennington** [discoproject/disco#32]
Running Disco 0.2.3 source distribution on ami-2946a740 (Debian Squeeze AMI from http://alestic.com/), with one master node and one remote slave, I was unable to run a job successfully. I went through all of the steps on the Troubleshooting Disco page, and found that the slave:start test failed with an {error, timeout} result. I tried a number of different flavors of node names (ec2 internal name, short names defined in /etc/hosts), and met with the same results. I was successfully able to run slave:start on the slave node to start a slave locally, but the same command from the master failed.

**Comment by joestump** [comment]
It seems I ran into this problem in us-west-1 as well. I've flooded the mailing list with (literally) hours of debugging information. I was running Ubuntu though.

I did some work with Jan and davisp from #couchdb and davisp said it appeared the slave module for Erlang was hosed. Maybe something is hosed in the Debian packages for the Erlang slave module?

**Comment by joestump** [comment]
I did some more digging and found this great overview of what might be going on:
http://tsung.erlang-projects.org/user_manual.html#htoc74

So I ran through all of the steps and _still_ can't get a remove slave to start up. Here's what I did.
1. I attempted to start a slave with:

<pre><code>
    root@ip-10-160-186-192:~# su - disco
    disco@ip-10-160-186-192:~$ erl -rsh ssh -sname master -setcookie SQKSFAXXNCLEFAIOKMUR
    Erlang R13B01 (erts-5.7.2) [source] [64-bit] [smp:2:2] [rq:2] [async-threads:0] [kernel-poll:false]

    Eshell V5.7.2  (abort with ^G)
    (master@master)1> slave:start(node1,disco,"-setcookie SQKSFAXXNCLEFAIOKMUR").
    {error,timeout}
    (master@master)2> 
</code></pre>

1. Erlang is installed and the same version/path on all nodes.
2. All of these nodes are in the same security group and in the same availability zone so I don't see a reason why packets would be blocked/dropped by any firewall. Not sure how I could test for this.
3. SELinux isn't installed. The only thing on the box that references it is `libselinux1`, which is required by many core/basic Debian packages.
4. My `/etc/hosts` file is properly setup as far as I can tell.

<pre><code>
    10.160.186.192  master ip-10-160-186-192
    10.160.187.63   node1 ip-10-160-187-63
    10.160.185.235  node2 ip-10-160-185-235

    127.0.0.1   localhost
</code></pre>

1. I can `ssh node1 erl` without issues from `master` as both `root` and `disco`.

I poked around Google a bit and couldn't find any references to bugs in the Erlang package on Debian.

**Comment by joestump** [comment]
I found two issues that cpennington might want to try to fix this. I just ran a successful job on my EC2/Ubuntu cluster with 1 master and 2 workers.
- I hadn't put the machines into the `default` security group.
- If you `su - disco` and then `ssh disco@node1`, `ssh disco@node2`, etc. you need accept each SSH identity from the master.

I'm guessing there's a way to turn SSH identification off on all nodes, which would likely help this issue.
