### ISSUE TITLE
Disco does not support Job in the main(...) module

### ISSUE THREAD

**Issue by JensRantil** [discoproject/disco#323]
This was first reported [here](https://groups.google.com/forum/#!searchin/disco-dev/jens$20rantil/disco-dev/j104HNkJkXU/oBG--1TjXOcJ) and later [here](https://mail.google.com/mail/u/0/#label/Forums/138b8b7b981a3693).

On a side-note, this issue makes [this code example](http://discoproject.org/doc/disco/faq.html#how-do-i-pass-the-output-of-one-map-reduce-phase-to-another) broken.

**Comment by pmundkur** [comment]
Lack of support noted in docs.
