### ISSUE TITLE
While building debian package build doesn't stop on error

### ISSUE THREAD

**Issue by larroy** [discoproject/disco#325]
ccache gcc -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -I/usr/include/python2.6 -c src/
discodbmodule.c -o build/temp.linux-x86_64-2.6/src/discodbmodule.o
src/discodbmodule.c:10:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'ccache' failed with exit status 1
make[4]: **\* [install] Error 1
make[4]: Leaving directory `/home/piotr/devel/disco/contrib/discodb'
make[3]: *** [install-discodb] Error 2
make[3]: Leaving directory`/home/piotr/devel/disco'
make[3]: Entering directory `/home/piotr/devel/disco'
(cd lib && DISCO_VERSION=0.4.3 DISCO_RELEASE=0.4.3 python2.7 setup.py install --root=/home/piotr/devel/disco/pkg/debian/python-disco/ --prefix=/usr/local --install-layout=deb --no-compile)
running install
running build

**Comment by pmundkur** [comment]
I'm not a debian expert, but the pkg/debian/control file clearly lists python-all-dev in Build-Depends, so Python.h should be required to build and should be checked by debhelper.  The rules file is very simple, it invokes debhelper.  If anything, these are bugs in debhelper.

**Comment by pmundkur** [comment]
Closing as this doesn't look like an issue within disco debian packaging.  Fwiw, the official debian packaging effort seems to have stalled: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=535891
