### ISSUE TITLE
Don't try to create disco user if already exists

### ISSUE THREAD

**Issue by larroy** [discoproject/disco#326]
I suggest something like this:

<pre>

diff --git a/pkg/debian/gen.create-disco-user.sh b/pkg/debian/gen.create-disco-user.sh
index 8e67155..b437589 100755
--- a/pkg/debian/gen.create-disco-user.sh
+++ b/pkg/debian/gen.create-disco-user.sh
@@ -7,8 +7,13 @@ set -e
 
 case "\$1" in
     configure)
-        adduser --system --quiet --group disco --disabled-password --shell /bin/bash --home ${RELSRV} --no-create-home
-        chown disco:disco ${RELSRV}
+        set +e
+        grep -q '^disco' /etc/passwd
+        if [  $? -ne 0 ];
+        then
+            set -e
+            adduser --system --quiet --group disco --disabled-password --shell /bin/bash --home ${RELSRV} --no-create-home
+            chown disco:disco ${RELSRV}
     ;;
 
</pre>

**Comment by pmundkur** [comment]
Fix pushed to master.
