### ISSUE TITLE
Error while creating debian package

### ISSUE THREAD

**Issue by larroy** [discoproject/disco#327]
dh_icons -O--with-python2
   dh_perl -O--with-python2
   dh_usrlocal -O--with-python2
dh_usrlocal: debian/disco-master/usr/local/bin/ddfs is not a directory
dh_usrlocal: debian/disco-master/usr/local/bin/disco is not a directory
        "rmdir debian/disco-master/usr/local/bin"
rmdir: failed to remove `debian/disco-master/usr/local/bin': Directory not empty
dh_usrlocal: rmdir debian/disco-master/usr/local/bin returned exit code 1
make[1]: *** [binary] Error 1
make[1]: Leaving directory`/home/piotr/devel/disco/pkg'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
make: **\* [../../Packages.gz] Error 2

**Comment by pmundkur** [comment]
Could you provide some details on platform (Debian/Ubuntu), platform version,  and debhelper version?

**Comment by larroy** [comment]
I was trying to build the package in Debian GNU/Linux testing (wheezy)

ii  debhelper                             9.20120608                         all          helper programs for debian/rules

Also in ubuntu 12.04  I get failure by:
dh_usrlocal: debian/disco-master/usr/local/share/disco/master/www/js/jquery-1.2.1.js is not a directory
dh_usrlocal: debian/disco-master/usr/local/share/disco/master/www/js/typewatch1.1.js is not a directory
dh_usrlocal: debian/disco-master/usr/local/share/disco/master/www/js/jquery.uitableedit.js is not a directory
dh_usrlocal: debian/disco-master/usr/local/share/disco/master/www/js/jquery-dom.js is not a directory
dh_usrlocal: debian/disco-master/usr/local/share/disco/master/www/js/config.js is not a directory
        "rmdir debian/disco-master/usr/local/share/disco/master/www/js"
rmdir: failed to remove `debian/disco-master/usr/local/share/disco/master/www/js': Directory not empty
dh_usrlocal: rmdir debian/disco-master/usr/local/share/disco/master/www/js returned exit code 1
make[1]: *** [binary] Error 1
make[1]: Leaving directory`/map_int/home/larroy/devel/disco/pkg'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
make: **\* [../../Packages.gz] Error 2

ii  debhelper                                     9.20120115ubuntu3                          helper programs for debian/rules

**Comment by pmundkur** [comment]
Hmm.  I'm able to build debian packages fine on Ubuntu 12.04 using debhelper 9.20120115ubuntu3, and Debian squeeze using debhelper 8.0.0.  I'm afraid we cannot test more debian versions than this.

**Comment by pmundkur** [comment]
Do you get the same error with the make-discoproject-debian script just pushed to the master?

**Comment by larroy** [comment]
This succeeds now in Debian.

**Comment by pmundkur** [comment]
Does it work for ubuntu as well?

**Comment by pmundkur** [comment]
Closing
