### ISSUE TITLE
worker should automatically package up all required modules without weird limitations

### ISSUE THREAD

**Issue by tubaman** [discoproject/disco#328]
Currently, the classic worker has some strange requirements for automatically detecting the required modules used in a job.  For example, packages aren't supported.  The classic worker should be changed to automatically detect all required modules(including packages).

**Comment by tubaman** [comment]
Here's a worker that meets the criteria:

https://gist.github.com/3515397

**Comment by pmundkur** [comment]
If you can add a test under tests/ for this, we can pull it.

**Comment by tubaman** [comment]
Cool.  We're a little fish in a big pond now here at Qualcomm so I'm
working through the open source request process.  As soon as the lawyers
release me, I can add the test.
- Ryan

**Comment by reidpr** [comment]
+1 for "weird limitations". imports are insanely confusing under Disco.

**Comment by pooya** [comment]
@tubaman Any updates on this? Could you please create a pull request?

**Comment by tubaman** [comment]
Sorry, I'm not actively using disco anymore and don't have time.

**Comment by pooya** [comment]
N worries. I'll see if I can get this tested and merged in.

**Comment by pooya** [comment]
The useful parts have been added to Disco.  Thanks.
