### ISSUE TITLE
Unable to run disco master and slave on same machine in 0.2.3

### ISSUE THREAD

**Issue by cpennington** [discoproject/disco#33]
While experimenting with 0.2.3, I found I couldn't run both
    disco master start
and
    disco worker start
at the same time. In particular, when starting the worker, I got a message to the effect of "lighttpd is already running with worker config". However, the only lighttpd process running was that with the master config file.

I also noticed that the MASTER_DISCO_PORT config parameter has been removed in 0.2.3, which I suspect is related. Does the master automatically start a worker as well? Or is there some other way of running both a master and slave on the same node?

**Comment by jflatow** [comment]
Yes, in 0.2.3 the master is automatically capable of being a worker (thus getting rid of DISCO_MASTER_PORT), if it is listed in your configuration. You should only need to start the master.

**Comment by cpennington** [comment]
Ah, that's good to know. I think I didn't catch the implication that that was how it worked in the Setting Up Disco docs, because I was expecting it to work like it did in 0.2.2

**Comment by tuulos** [comment]
wontfix
