### ISSUE TITLE
Disco does not work on erlang R15B02

### ISSUE THREAD

**Issue by jseabold** [discoproject/disco#330]
Took me a while to figure out why this wasn't working, but I couldn't run the count_words.py example. Downgraded to erlang R14B04 and it worked as expected. The error message at the console was something like 

```
[error] gen_server <10152.65.0> terminated with reason: bad argument in {erlang,open_port,[{spawn,[110,105
<snip>
```

Not sure if you're targeting supporting this or not, but it's here in case someone else runs into it.

**Comment by pmundkur** [comment]
We'll push a fix to master soon.   In the meantime, could you try this patch: https://gist.github.com/3855955?

**Comment by plorent** [comment]
The patch works.

**Comment by pmundkur** [comment]
Fixed in master.
