### ISSUE TITLE
jobargs

### ISSUE THREAD

**Issue by xhancar** [discoproject/disco#331]
The documentation for the Job.run method
( http://discoproject.org/doc/disco/lib/job.html?highlight=job.run#disco.job.Job.run )
says

Parameters: jobargs (dict) – runtime parameters for the job. Passed to the disco.worker.Worker methods listed above, along with the job itself.

But AFAIK the parameters for Job.run are on this page:
http://discoproject.org/doc/disco/lib/worker/classic.html

i.e. in  disco.worker.classic.worker.Worker

(if somehow it is not a mistake, definitely it is not intuitive)

**Comment by pmundkur** [comment]
Documentation hopefully clarified in 0.4.4; website will be updated on release.
