### ISSUE TITLE
OSX 10.7.5 - no access to localhost

### ISSUE THREAD

**Issue by plorent** [discoproject/disco#332]
I've installed disco on my MBP according to the instructions but keep getting this error when running disco nodaemon:

12:24:00.371 [info] Starting node "disco_8989_slave" on "localhost" ("localhost")
ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory
ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory
ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory
Permission denied (publickey,keyboard-interactive).

Although I've granted access to 'all users' under System Preferences->Sharing->Remote Login and have tried resolving the issue using https://github.com/markcarver/mac-ssh-askpass I keep running into the same issue.

Do you have any ideas on how to resolve this?

**Comment by pmundkur** [comment]
You could try asking on the disco mailing list.  I'm afraid primary development is currently being done on Linux only; the primary Mac developers are currently inactive.

**Comment by pmundkur** [comment]
What was the resolution for this?  We could add it to the troubleshooting doc in the next release.

**Comment by spil-peter-lorent** [comment]
One of our system engineers helped me out. I believe he added private and public keys for disco (id_rsa_disco and id_rsa_disco.pub) and changed the disco user in settings.py to the name of my account on my machine.
