### ISSUE TITLE
gracefully handle non-list single input values 

### ISSUE THREAD

**Issue by NicolasNeubauer** [discoproject/disco#334]
When the input parameter ro Job.run is a single URL string, it needs to be put into a list. If not, Disco - expecting a sequence of URLs - will iterate over each character in the string. Interestingly, the result of this is the job being executed without any mistakes, except there isn't any input (unless you have single-character tags). So I'd propose to
- auto-wrap single string values for input, or
- create a meaningful error message if a string is detected.

**Comment by fsaintjacques** [comment]
+1

**Comment by pmundkur** [comment]
Fixed for 0.4.4
