### ISSUE TITLE
Debian package broken?

### ISSUE THREAD

**Issue by sajal** [discoproject/disco#339]
Today when i tried to install disco from the official disco debian repository  (http://discoproject.org/doc/disco/start/download.html#debian-packages) , I get an error.

````apt-get install python-disco
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-disco : Depends: python (< 2.7) but 2.7.3-0ubuntu2 is to be installed
E: Unable to correct problems, you have held broken packages.````

`root@ip-xxx:~# uname -a
Linux ip-10-196-122-191 3.2.0-27-virtual #43-Ubuntu SMP Fri Jul 6 14:45:58 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
root@ip-10-196-122-191:~# python --version
Python 2.7.3
root@ip-xxx:~#`

I install from the repository every couple of days or so (on EC2 spot instance) and the install failed today. Probably something broke in the new release yesterday?

Can I install an older release using apt-get itself? Just dont want to install it by hand...

**Comment by sajal** [comment]
ok i could manually install these 4.3 from ..

http://discoproject.org/debian/python-disco_0.4.3_all.deb
http://discoproject.org/debian/disco-node_0.4.3_amd64.deb
http://discoproject.org/debian/disco-master_0.4.3_all.deb

Those packages install without any fuss using dpkg

In control script for python-disco 0.4.3

```
Depends: python (>= 2.6), python-support (>= 0.90.0)
```

for 0.4.4

```
Depends: python2.6, python (>= 2.6.6-3+squeeze3~), python (<< 2.7)
```

Maybe that has something to do with the dependency issues?

**Comment by pmundkur** [comment]
Hmm, perhaps debhelper macros cause more problems than they solve.   Thanks for catching this.

**Comment by pmundkur** [comment]
Unfortunately, that line is inserted by ${python:Depends}, which is required by http://wiki.debian.org/Python/Policy (see pt 2).  I suggest you use the make-discoproject-debian script to build your own local debian packages.

**Comment by sajal** [comment]
hmm... running make-discoproject-debian on my local machine (ubuntu 11.10 ) puts in ...

Depends: python2.7 | python2.6, python (>= 2.7.1-0ubuntu2), python (<< 2.8)

... which makes it compatible with 2.7.x being shipped with python currently... I have never dabbled in python packaging before... but how about disco having an official ppa at https://launchpad.net/ ?  They do the package build for you for various ubuntu distributions.

**Comment by pmundkur** [comment]
I'm afraid we have our hands full developing and running disco already.  That could be something enterprising Disco users could take up.   I'll close this bug since our Debian packages are unsupported.

**Comment by sajal** [comment]
I guess ill try to take this up as a holiday season project... Always wanted to try my hand at packaging ubuntu debs... will report back if I have any success.

**Comment by danielpizarro** [comment]
@pmundkur it they are really unsupported, then this part of documentantion should be removed:https://disco.readthedocs.org/en/0.4.5/start/download.html#debian-packages .

Links are broken anyway.

**Comment by pmundkur** [comment]
Daniel, I don't maintain/develop Disco anymore.  Perhaps you could
bring this up on the mailing list?
