### ISSUE TITLE
Troubleshooting section not updated for 0.2.3

### ISSUE THREAD

**Issue by adriaant** [discoproject/disco#34]
http://discoproject.org/doc/start/troubleshoot.html#troubleshooting contains suggestions that don't work for 0.2.3. For example, `erl -boot master/disco` cannot be done. I'm trying to figure out why I cannot start the master on a Linux box

**Comment by jflatow** [comment]
updated docs with new features/API changes. Closed by 9cd9b6f1c145d79e3a099fa490e6630470527be8. Closed by 9cd9b6f1c145d79e3a099fa490e6630470527be8.
