### ISSUE TITLE
'utf8' codec can't decode byte 0xd5 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by xhancar** [discoproject/disco#341]
$ disco jobdict  dispipe@54b:37485:6c06
dispipe@54b:37485:6c06
'utf8' codec can't decode byte 0xd5 in position 0: invalid continuation byte

**Comment by pmundkur** [comment]
Fixed.

**Comment by ConstantinSco** [comment]
Could you show me your code?I meet this fault
'utf-8' codec can't decode bytes in position 138-139: invalid continuation byte
Thanks.
