### ISSUE TITLE
ddfs chunk fails with grep example

### ISSUE THREAD

**Issue by cholcombe973** [discoproject/disco#343]
I used ddfs chunk to put a log file into the cluster.  When I ran the grep example it produced some strange output.  bse on the irc channel had a suspicion: 
if this works and the "ddfs chunk" didn't, then it'd signal a likely bug in the chunk operation assuming unicode when it shouldn't or otherwise doing something daft when there is a stray widechar in there

The problem resolves itself if I split the file with the split command and use the ddfs push instead.  That works as expected.  

The problem also doesn't occur if I use the full path of the file on the localhost instead of a tag.  

I am using the latest git code to test with across my cluster.  I am attaching a tiny portion of my log file that is showing the problem.

**Comment by cholcombe973** [comment]
Actually I'm not sure if I can attach this log file.  There's lots of sensitive data in there I have to clean out first.

**Comment by pmundkur** [comment]
The grep example (in examples/util/grep.py) assumes normal text input data, not data that has been chunked.  To read chunked data, you need to use the chain_reader to parse the input.   So, just modify your script as follows:

from disco.job import Job
from disco.worker.classic.func import nop_map, chain_reader

class Grep(Job):
    map = staticmethod(nop_map)
    params = r''

```
@staticmethod
def map_reader(fd, size, url, params):
import re
    pattern = re.compile(params)
    fd = chain_reader(fd, size, url, params)
for line in fd:
        if pattern.match(line):
    yield url, line
```
