### ISSUE TITLE
support sys.stdout.isatty()

### ISSUE THREAD

**Issue by reidpr** [discoproject/disco#351]
Steps to reproduce:
- Call `sys.stdout.isatty()` from within a Disco job.

Actual behavior:

```
AttributeError: 'MessageWriter' object has no attribute 'isatty'
```

Expected behavior:
- Return value is 0.

Comments:
- This is a common way to determine if various terminal stuff on standard out is supported. In a Disco job, the answer is no, so `isatty()` should exist on `MessageWriter` (or something -- I'm still a n00b with Disco) and return 0.

**Comment by pooya** [comment]
commit a150a370b30cf886a1fbe375880913ee02814b3b adds this feature.  Thanks.
