### ISSUE TITLE
Question about DDFS.

### ISSUE THREAD

**Issue by Alexav92** [discoproject/disco#352]
Hi! I have just started trying to solve my problems with disco and have a question. In my cluster i have non hard drive nodes and separated data storage. OS on nodes is network loading. Can i use disco in this conditions? Can i store ddfs in my NFS? 
P.S. sorry for my bad english

**Comment by pmundkur** [comment]
You should direct such questions to the mailing list; but the answer in short is that yes, you can, but it will not perform well at all.
