### ISSUE TITLE
URL to checkov.txt is 404

### ISSUE THREAD

**Issue by TTimo** [discoproject/disco#353]
In the test program referenced in the documentation and on the website: examples/util/count_words.py

The URL to http://discoproject.org/media/text/chekhov.txt is 404

Did a brief google search but I'm not finding a replacement. Any suitable large text file would be ok :)

**Comment by TTimo** [comment]
Note that bigfile.txt reference here: http://disco.readthedocs.org/en/latest/start/tutorial.html is 404 as well.

**Comment by andrewelkin** [comment]
20 days passed. It seems that there is nobody there .. Shame.. the project seemed to be a nice one.

**Comment by pmundkur** [comment]
I've restored these missing files (chekhov + bigfile) to the website.  Apologies for the lateness, non-disco life got quite busy suddenly (still is).
