### ISSUE TITLE
Cannot add new hosts on the configuration page

### ISSUE THREAD

**Issue by TTimo** [discoproject/disco#354]
The configuration page does not let me add new nodes. I can type in the name of a node, but after typing it, when I click on the text box again, or anywhere else (the save button for instance), it just disappears. There is no error feedback.

Tried Chrome, FireFox and Safari on a MacOS X 10.8
![screen shot 2013-08-20 at 2 49 54 pm](https://f.cloud.github.com/assets/6637/996540/1b1eb2d0-09d2-11e3-8152-9bdce5d1d7c0.png)

If I try to save, or click on the max worked cell, or anything else, the text entry disappears:

![screen shot 2013-08-20 at 2 49 47 pm](https://f.cloud.github.com/assets/6637/996541/2008ca92-09d2-11e3-9592-13ad46790eed.png)

**Comment by TTimo** [comment]
Since there is a bit of confusion: the cluster is Linux machines (Ubuntu 12.x on AWS). Using latest disco github code.

I only mentioned OSX because sometimes the particular browser/OS matters in web bugs. Considering the problem in this case, it's likely any web browser will show the issue, and it's really a bug on the server side though.

**Comment by pmundkur** [comment]
This was an issue in a 3rd party js library.  I've pushed a fix to master.  Please let me know if it now works for you.

**Comment by TTimo** [comment]
Great news! We can probably close this .. I did process the data I was after with disco, but I don't have any further work scheduled with it atm.
