### ISSUE TITLE
After installation Web looks OK, jobs do not start hanging with black screen

### ISSUE THREAD

**Issue by andrewelkin** [discoproject/disco#358]
After installation : running  count_words.py  example  - with patched input file name of course.  Job does not appear in the jobs list on 8989 web page,  python count_words.py gives no output and hangs until Ctrl-C.

**Comment by pooya** [comment]
Would you please provide us with the configuration (OS, Python version, Erlang version, disco version) when you hit this issue?

**Comment by pooya** [comment]
Closing as not reproducible.
