### ISSUE TITLE
disk_sort failes with "UnpicklingError: pickle data was truncated"

### ISSUE THREAD

**Issue by rsommer** [discoproject/disco#361]
In https://github.com/discoproject/disco/blob/0.4.5/lib/disco/worker/classic/func.py:

The re_reader iterates over key/value-pairs separated by \xff and \x00.

In disk_sort, where the file to be read by re_reader is written, for the key their is a sanity check, for the value their is not. If your value happens to contain a \x00-byte, the pickle-string gets only partially read afterwards and leads to the "UnpicklingError: pickle data was truncated" error in https://github.com/discoproject/disco/blob/0.4.5/lib/disco/worker/classic/func.py#L532 while trying to unpickle.

A simple python object containig a \x00 byte when pickled using protocol 0 would be

``` python
obj = {"key": u"\u0000"}
```

Possible workaround: encode the pickle_dumps with .encode("hex")

**Comment by pooya** [comment]
About the encoding workaround:
1. How does it guarantee that the output does not have \x00 ?
2. Encoding the pickled string doubles its size.
There should be a better way.

**Comment by pooya** [comment]
af7f7118ad917656064c7fd0dd7fe2a3147f79b2 should fix this issue. It will be merged into mainline shortly.
