### ISSUE TITLE
Documentation for disc.worker.task_io missing

### ISSUE THREAD

**Issue by JensRantil** [discoproject/disco#366]
I notice that http://disco.readthedocs.org/en/latest/lib/worker/classic.html#disco.worker.classic.worker.Worker refers to `disc.worker.task_io`, but I can't find that module documented on http://disco.readthedocs.org/en/latest/lib/.

Expected: That it is listed.

**Comment by pooya** [comment]
The doc is added with f8c624d59779aeb2cc55add11e320c67eac42047 in the develop branch.
Thanks!
