### ISSUE TITLE
The test test_chain.DavinChainTestCase fails.

### ISSUE THREAD

**Issue by pooya** [discoproject/disco#378]
The http request is for no apparent reason.

**Comment by pmundkur** [comment]
I suspect the reason for the keep-alive is that if the clients don't
close the ddfs connections, the disco nodes could run out of file
descriptors.  For large jobs, there are a huge number of connections
made per DDFS node.

Disabling it in the init function makes sense.

**Comment by pooya** [comment]
Thanks. It should be fixed with 187c66c.
