### ISSUE TITLE
Disco Dashboard UI - worker status boxes are too big

### ISSUE THREAD

**Issue by tspurway** [discoproject/disco#390]
![worker](https://f.cloud.github.com/assets/25276/1891424/037d3cba-7a3d-11e3-8733-8a28839a3659.png)

In the image, we can see that the worker boxes wrap around to the next line, obscuring the disk usage indicator on the next line.

**Comment by pooya** [comment]
Fixed with 86735700ea2fbeefd9c307ca6a58cdbe6c93f00a
