### ISSUE TITLE
connection timeout and erl crash

### ISSUE THREAD

**Issue by xiufengliu** [discoproject/disco#41]
Hi, I have configure a cluster with two computers, xiliu-fedora (master) and xiliu-public (worker). Both are running Fedora 11, python 2.6.3. However, I did alway get following timeout errors, and on the worker node, erl is crash, and throws erl_crash.dump 

---

2009/10/08 19:20:36master

map:0 added to waitlist

2009/10/08 19:20:36xiliu-public

WARN: [map:0] Node failure: "Couldn't connect to xiliu-public (timeout). Node blacklisted temporarily."

2009/10/08 19:20:04master

map:0 assigned to xiliu-public

2009/10/08 19:20:04master

map:0 added to waitlist

2009/10/08 19:20:04master

Map phase

2009/10/08 19:20:04master

Starting job

2009/10/08 19:20:04master

New job!

---

[xiliu@xiliu-public ~]$ tail -f erl_crash.dump 
timeout
infinity
fun
''
'$end_of_table'
'nonode@nohost'
'_'
true
false
=end
^C

**Comment by tuulos** [comment]
solved
