### ISSUE TITLE
Disco Dashboard UI - job name is difficult to 'copy'

### ISSUE THREAD

**Issue by tspurway** [discoproject/disco#410]
A very common operation is to copy the job name so that you can use it on a command line.  Right now it runs together with the 'job:' string, and is annoyingly difficult to highlight.  Maybe we need a 'copy to buffer' button beside it?  At the very least we should put it in it's own header or paragraph in the HTML (h2?)

**Comment by pooya** [comment]
This should be resolved with commit: a7538bc68f
