### ISSUE TITLE
Support chunk size parameter in `ddfs chunk` CLI command

### ISSUE THREAD

**Issue by kszucs** [discoproject/disco#424]
Currently we can't set the chunk size using the command line, which would be handy in some cases. 
This modification only needs a new option to be forwarded to ddfs.chunk method.

**Comment by pooya** [comment]
That is a good feature.  Will be added in the version after 0.5.

**Comment by pooya** [comment]
This should be resolved with commit 1f127f6e544edca7a915837ea2880988e3f6ed68
