### ISSUE TITLE
disco 0.5: can't run make 

### ISSUE THREAD

**Issue by gijzelaerr** [discoproject/disco#440]
OS: Ubuntu Trusty (14.04) & Ubuntu precise (12.04)
Disco: 0.5 (release tarball)
error:

```
==> master (compile)
Compiled src/disco_util.erl
Compiled src/lock_server.erl
Compiled src/disco_main.erl
Compiled src/fair_scheduler.erl
Compiled src/json_validator.erl
[...]
Compiled src/fair_scheduler_fifo_policy.erl
Compiled src/node_mon.erl
Compiled src/worker_runtime.erl
Compiled src/disco_server.erl
ERROR: git describe --always --tags `git log -n 1 --pretty=format:%h .` failed with error: 128 and output:
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
```

You can easily replicate the problem using docker:
https://github.com/gijzelaerr/discodocker
If you try it, please check if the correct script is ran (stable or dev build)

**Comment by gijzelaerr** [comment]
this can be solved by using the branch directly (not the tarball):

`git clone https://github.com/discoproject/disco/tree/0.5`

But probably you want to have your tarballs working also.

**Comment by pooya** [comment]
Thanks!
We mention that disco cannot be built with the tarball:
http://disco.readthedocs.org/en/latest/start/download.html
I'll leave this issue open to make sure we put that note in a more visible place.

**Comment by gijzelaerr** [comment]
you're right, I missed that one.
