### ISSUE TITLE
disco master and 0.5: can't find include lib "kernel/include/file.hrl" (ubuntu precise)

### ISSUE THREAD

**Issue by gijzelaerr** [discoproject/disco#441]
OS: Ubuntu Precise (12.04)
erlang:1:14.b.4
disco: 0.5, master branch (469dc4c50d21aa0fdfd6d5ae1ca3d6de128d1745)
error:

```
==> folsom (get-deps)
Pulling bear from {git,"git://github.com/campanja/bear.git",
                       {tag,"0.8.0-cmpj1"}}
Cloning into 'bear'...
Pulling meck from {git,"git://github.com/eproxus/meck","master"}
Cloning into 'meck'...
==> bear (get-deps)
==> meck (get-deps)
==> mochiweb (get-deps)
==> goldrush (compile)
Compiled src/gr_manager_sup.erl
Compiled src/glc_lib.erl
Compiled src/gr_counter.erl
Compiled src/gr_context.erl
Compiled src/gr_manager.erl
Compiled src/gre.erl
Compiled src/gr_counter_sup.erl
Compiled src/gr_sup.erl
Compiled src/glc_ops.erl
Compiled src/gr_param_sup.erl
Compiled src/glc.erl
Compiled src/gr_app.erl
Compiled src/gr_param.erl
Compiled src/glc_code.erl
==> lager (compile)
src/lager_util.erl:19: can't find include lib "kernel/include/file.hrl"
src/lager_util.erl:137: record file_info undefined
src/lager_util.erl:138: record file_info undefined
src/lager_util.erl:149: record file_info undefined
src/lager_util.erl:152: record file_info undefined
make: *** [master] Error 1
```

**Comment by gijzelaerr** [comment]
This issue can be resolved by installing the `erlang-dev` and `erlang-parsetools` packages.

**Comment by saa** [comment]
Hi. I use this https://www.erlang-solutions.com/downloads/download-erlang-otp repo for erlang. There is always the latest version with all the necessary.

**Comment by gijzelaerr** [comment]
ok, sounds good also. But I think adding a note to the documentation that on plain debian/ubuntu you need to install more than the core erlang package would prevent this mistake for others in the future.

**Comment by gijzelaerr** [comment]
I was using the `erlang-base` ubuntu package, which doesn't install all erlang sub packages. If you install `erlang`, above mentioned packages will be installed automatically. Stupid me, sorry for wasting your time!
