### ISSUE TITLE
can't run example from documentation - job submission failed

### ISSUE THREAD

**Issue by gijzelaerr** [discoproject/disco#443]
When I install disco following the documentation I fail at the example:

```
python /disco/examples/util/count_words.py
Job@571:51da8:59289:
Traceback (most recent call last):
  File "/disco/examples/util/count_words.py", line 16, in <module>
    for word, count in result_iterator(job.wait(show=True)):
  File "/usr/local/lib/python2.7/dist-packages/disco/core.py", line 367, in wait
    event_monitor.refresh()
  File "/usr/local/lib/python2.7/dist-packages/disco/eventmonitor.py", line 184, in refresh
    status = self.status
  File "/usr/local/lib/python2.7/dist-packages/disco/eventmonitor.py", line 175, in status
    .format(tuple(self.stats)))
  File "/usr/local/lib/python2.7/dist-packages/disco/eventmonitor.py", line 166, in stats
    first = pipeline[0]
IndexError: list index out of range
```

Everything seems to be configured correctly, single machine, disco is running, ssh to localhost works.

disco console output:

https://gist.github.com/gijzelaerr/9208805

**Comment by pooya** [comment]
@gijzelaerr Would you please also provide us with the output of following command
echo $LANG
also the python version you are using:
python --version
and erlang version:
erl version
Thanks.

**Comment by gijzelaerr** [comment]
```
$ echo $LANG

$ python --version
Python 2.7.3
$ erl version
Erlang R14B04 (erts-5.8.5) [source] [64-bit] [smp:2:2] [rq:2] [async-threads:0] [kernel-poll:false]
```

**Comment by pooya** [comment]
Status: I have reproduced this problem on docker.

**Comment by gijzelaerr** [comment]
note that it is not docker specific, I have the same problem while running the same normal (not inside docker) ubuntu and installed packages.

**Comment by gijzelaerr** [comment]
i've discovered what is the source of this problem, a missing erlang subsystem. Debian splits up all erlang modules in various packages. I don't know why, but I was using the `erlang-base` only package, that only installs the core and not various libraries. There is also an `erlang` package that installs all the submodules. If you want I can update the docker file to install the full erlang.

**Comment by pooya** [comment]
Thanks @gijzelaerr
