### ISSUE TITLE
Problem when connecting node in the disco 0.5

### ISSUE THREAD

**Issue by ZheniaZh** [discoproject/disco#446]
Hello, I there was a following unpleasant situation:
I have two compute nodes (node00 = disco-master, node01 = disco-node). On one of these I installed disco-master. 
Everything was done according to the instructions as follows:
    I downloaded the new version of disco: git clone    git://github.com/discoproject/disco.git       /home/user/src/disco
   cd /home/user/src/disco && sudo make
   sudo make install.
 In the folder /etc/disco/settings.py set values: 
    DDFS_TAG_MIN_REPLICAS = 1 
    DDFS_TAG_REPLICAS = 1 
    DDFS_BLOB_REPLICAS = 1
The documentation says that to work with the disco, you can create separate user (http://disco.readthedocs.org/en/latest/start/install_sys.html, section Creating a disco user). 
I did so, created a new user called "disco". Home directory of the user - /usr/local/var/disco.
Next, I generated public keys for users "user" and "disco". Generated keys recorded in the authorized_keys file:
    user.node00.pub --> /home/user/.ssh/authorized_keys
    disco.node00.pub --> /usr/local/var/disco/authorized_keys

I then installed a disco on node:
    git clone git://github.com/discoproject/disco.git       /home/user/src/disco
    cd /home/user/src/disco && sudo make
    sudo make install-node.
By analogy with the disko-master I created a user "disco" with the same home directory(/usr/local/var/disco/). 
  Also generated public keys and recorded them in a authorized_keys file:
      user.node01.pub --> /home/user/.ssh/authorized_keys
      disco.node01.pub --> /usr/local/var/disco/authorized_keys
Then I exchanged keys between nodes:
     user@node00$: sudo scp /home/user/.ssh/user.node00.pub  node01:/home/user/.ssh/  and and recorded: user.node00.pub -->  /home/user/.ssh/authorized_keys. Then did the same in the reverse direction.
The same was done for users disco. 
 Thus, on both nodes in the files /usr/local/var/disco/authorized_keys and /home/user/   contains two keys.

Next tried to adjust the Erlang. To do this, on the disco-master did the following:
     user@node00$:sudo -u disco chmod 400 ~/.erlang.cookie (originally located in /home/user).
     user@node00$:  sudo cp /home/user/.erlang.cookie   /usr/local/var/disco.
     user@node00$:  sudo scp /home/user/.erlang.cookie   node01/home/user/

Then, on an ordinary node did: 
    user@node01$:  sudo cp /home/user/.erlang.cookie   /usr/local/var/disco.

Then I ran the disco:
    sudo disco start
In the web-interface, added two nodes. When i added node01 came connection request, shown in figure by reference
![image](https://f.cloud.github.com/assets/6796138/2273594/8450ad82-9f12-11e3-820c-446c029b25ab.png)
I understand disco running as user root.I understood that disco running as user root. Another user can not start the disco.

I entered the command ps aux | grep beam. \* disco and received the following;
![image](https://f.cloud.github.com/assets/6796138/2273746/5d85be5c-9f14-11e3-8a83-5ea6090f31be.png).

Then I did authenticate the file /etc/ssh/authorized_keys. In this file recorded six keys - two nodes with three users (user, disco, root). This operation is made ​​on both nodes.
After this problem with ssh-connection have been resolved. But the second node still remained nonworking. 

I have a problem with where to put the file. erlang.cookie. In the log file contained the following information: 
....
     2014-02-26 17:08:24.862 [error] emulator Error in process <0.39.0> on node     'disco_8989_slave@node01' with exit value:   {{badfun,#Fun<node_mon.10.50253045>},[{erlang,apply,2,[]}]}
2014-02-26 17:08:24.865 [info] <0.4736.0>@node_mon:wait:78 Node failed at disco_8989_slave@node01 on "node01": {{badfun,#Fun<node_mon.11.50253045>},[{error_handler,undefined_lambda,3,[{file,"error_handler.erl"},{line,67}]}]}
2014-02-26 17:08:24.865 [info] <10470.40.0> lock_server starts on disco_8989_slave@node01 
.....
    In this occasion I have a few questions:
1. Is it possible to do without creating a separate user "disco"?
2. After creating a user "disco" whether to change the value of a variable to a value DISCO_USER "disco" ? (In my case, вy default DISCO_USER = "user")
3. When installing disco on the node01 in the /usr/local/var/disco were not created the data and ddfs directories. Is this normal?
4. What steps have been made ​​by me is not correct installation and configuration disco ?

**Comment by pooya** [comment]
@ZheniaZh 
Hi
- By default the develop branch is checked out when you clone the repository.  You should do
  $ git checkout 0.5
  to checkout a stable release.
- I got a little confused about the things that you mentioned about ssh. Try to ssh to node00 and node01 from both node00 and node01 and if all of them succeed without requiring password, ssh is configured properly.  From the picture it seems like ssh is not configured properly.
- Have you seen this page? http://disco.readthedocs.org/en/latest/start/troubleshoot.html
- Make sure the user has permission for creating the ddfs directory.  Although if it does not have permission the error will say so.
- From the error message, it seems like disco is not installed properly on the slave node.  Just to make sure do a full install on this node too:
  user@node01$ sudo make install

**Comment by ZheniaZh** [comment]
Thanks, I want to know whether it is possible to do without creating a user "disco"? As an option use a to run of the disco by the user "user", since the default DISCO_USER = "user". The fact is that the documentation about it says nothing.  
I saw page http://disco.readthedocs.org/en/latest/start/troubleshoot.html. I have a problem that is described in section Is SSH working (disco debug). 
I disco runs only on behalf of the user "root". Is it possible to somehow change?

**Comment by ZheniaZh** [comment]
After the command git checkout 0.5 was deduced as follows:
Note: checking out '0.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 90db88d... Add the release date for 0.5.

**Comment by pooya** [comment]
@ZheniaZh I think the easiest way is to just use you own (non-root) user for using disco.
The steps should be simple:
1. install disco
2. setup ssh
3. Make sure you have permission for the disco home (DISCO_HOME in /etc/disco/settings.py).

There are a lot of ways for setting up password-less ssh.  Just search for it in the internet.

The output you got from checking out the tag is expected.  You only have to check out a branch if you want to make changes to the code.

**Comment by ZheniaZh** [comment]
I reinstalled disco, but again there was a problem:

user@node00:~/src/disco$ disco nodaemon
{error_logger,{{2014,2,28},{0,1,52}},"Protocol: ~p: register error: ~p~n",["inet_tcp",{{badmatch,{error,duplicate_name}},[{inet_tcp_dist,listen,1,[{file,"inet_tcp_dist.erl"},{line,70}]},{net_kernel,start_protos,4,[{file,"net_kernel.erl"},{line,1314}]},{net_kernel,start_protos,3,[{file,"net_kernel.erl"},{line,1307}]},{net_kernel,init_node,2,[{file,"net_kernel.erl"},{line,1197}]},{net_kernel,init,1,[{file,"net_kernel.erl"},{line,357}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}]}
{error_logger,{{2014,2,28},{0,1,52}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.20.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,320}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}},{ancestors,[net_sup,kernel_sup,<0.9.0>]},{messages,[]},{links,[#Port<0.342>,<0.17.0>]},{dictionary,[{longnames,false}]},{trap_exit,true},{status,running},{heap_size,987},{stack_size,24},{reductions,531}],[]]}
{error_logger,{{2014,2,28},{0,1,52}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[[disco_8989_master,shortnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2014,2,28},{0,1,52}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,shutdown},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2014,2,28},{0,1,52}},std_info,[{application,kernel},{exited,{shutdown,{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}})
Failed to start Master node00:8989

**Comment by ZheniaZh** [comment]
Ran "disco" with the command disco start and checked test example:
user@node00:~/src/disco/examples/util$ python count_words.py
Job@571:81f09:8da79:
Traceback (most recent call last):
  File "count_words.py", line 16, in <module>
    for word, count in result_iterator(job.wait(show=True)):
  File "/usr/local/lib/python2.7/dist-packages/disco/core.py", line 367, in wait
    event_monitor.refresh()
  File "/usr/local/lib/python2.7/dist-packages/disco/eventmonitor.py", line 185, in refresh
    self.log_events()
  File "/usr/local/lib/python2.7/dist-packages/disco/eventmonitor.py", line 178, in log_events
    for offset, (timestamp, host, message) in self.events:
  File "/usr/local/lib/python2.7/dist-packages/disco/eventmonitor.py", line 157, in events
    return self.job.events(self.offset)
  File "/usr/local/lib/python2.7/dist-packages/disco/core.py", line 244, in events
    return event_iter(self.rawevents(jobname, offset=offset))
  File "/usr/local/lib/python2.7/dist-packages/disco/core.py", line 248, in rawevents
    offset=offset)
  File "/usr/local/lib/python2.7/dist-packages/disco/core.py", line 61, in request
    offset=offset)
  File "/usr/local/lib/python2.7/dist-packages/disco/comm.py", line 89, in download
    headers=headers).read()
  File "/usr/local/lib/python2.7/dist-packages/disco/comm.py", line 80, in request
    raise CommError(response.read(), url, status)
disco.error.CommError: Unable to access resource (http://node00:8989/disco/ctrl/rawevents?name=Job@571:81f09:8da79): Not found. (404)

**Comment by pooya** [comment]
I think this error is saying that you are already running another disco instance.  Please kill the other beam processes and then start disco.

**Comment by ZheniaZh** [comment]
Wanted to know again disco node installed using "sudo make install" or "sudo make install-node" ?

**Comment by pooya** [comment]
The node can be installed with install-node.  But if you run sudo make install, it will install the necessary stuff for the slaves as well as some other things so it should work fine in this case.

**Comment by ZheniaZh** [comment]
Thank you, I have worked out!
