### ISSUE TITLE
'make debian' is failing on Ubuntu 12.04LTS x64

### ISSUE THREAD

**Issue by vlebedev** [discoproject/disco#455]
Looks like python files are going in a wrong place, here is a tail of make log file:
`
D: dh_python2:584: processing package python-discodb...
W: dh_python2:90: Python 2.7 should install files in /usr/lib/python2.7/dist-packages/. Did you forget "--install-layout=deb"?
D: dh_python2:94: moving files from debian/python-discodb/usr/local/lib/python2.7/dist-packages to debian/python-discodb/usr/lib/python2.7/dist-packages/
D: dh_python2:464: package python-discodb details = {'requires.txt': set([]), 'shebangs': set([]), 'compile': True, 'ext': set([(2, 7)]), 'nsp.txt': set([]), 'public_vers': set([(2, 7)]), 'private_dirs': {}}
D: dh_python2:584: processing package disco-node...
D: dh_python2:464: package disco-node details = {'requires.txt': set([]), 'shebangs': set([]), 'compile': False, 'ext': set([]), 'nsp.txt': set([]), 'public_vers': set([]), 'private_dirs': {}}
   dh_usrlocal
dh_usrlocal: debian/disco-master/usr/local/share/disco/master/www/favicon.ico is not a directory
dh_usrlocal: debian/disco-master/usr/local/share/disco/master/www/index.html is not a directory
dh_usrlocal: debian/disco-master/usr/local/share/disco/master/www/job.html is not a directory
dh_usrlocal: debian/disco-master/usr/local/share/disco/master/www/config.html is not a directory
dh_usrlocal: debian/disco-master/usr/local/share/disco/master/www/images/logo.png is not a directory
"rmdir debian/disco-master/usr/local/share/disco/master/www/images"
rmdir: failed to remove 'debian/disco-master/usr/local/share/disco/master/www/images': Directory not empty
dh_usrlocal: rmdir debian/disco-master/usr/local/share/disco/master/www/images returned exit code 1
make[2]: *** [binary] Error 1
make[2]: Leaving directory '/home/disco/disco/pkg'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
make[1]: *** [../../Packages.gz] Error 2
make[1]: Leaving directory '/home/disco/disco/pkg/debian'
make: *** [debian] Error 2
`

**Comment by pooya** [comment]
This should be resolved with commit ff0142a33a249a4f398e49c74df94c141e852056.
