### ISSUE TITLE
can't run nodaemon with latest master: bad scheduling option -scl

### ISSUE THREAD

**Issue by gijzelaerr** [discoproject/disco#461]
I get an error running the latest disco develop branch (192984d791459b9cec1729b44d30a4bda6b09644):

root@machine:/# /usr/local/bin/disco nodaemon
bad scheduling option -scl
Usage: beam.smp [flags] [ -- [init_args] ]

OS: Ubuntu 12.04 64bit
erlang: 1:14.b.4-dfsg-1ubuntu1

**Comment by pooya** [comment]
Thanks for reporting this.  Please reopen if the issue persists.
