### ISSUE TITLE
disco stageresults prints in Python style format

### ISSUE THREAD

**Issue by tspurway** [discoproject/disco#465]
I get the following result from the disco stageresults command:

`➜  ~  disco stageresults select_from___test_imps@573:be963:5de17 -S restrict-select
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-0-1395780644149099.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-1-1395780644148106.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-2-1395780644163804.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-3-1395780644170449.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-4-1395780644461914.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-5-1395780644479152.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-6-1395780644486731.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-7-1395780644500817.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-8-1395780644778113.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-9-1395780644797303.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-10-1395780644827501.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-11-1395780644848981.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-12-1395780645106284.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-13-1395780645122168.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-14-1395780645159419.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-15-1395780645187674.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-16-1395780643800697.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-17-1395780643801191.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-18-1395780643800157.results',)
(u'dir://tim/disco/tim/d2/select_from___test_imps@573:be963:5de17/.disco/restrict-select-19-1395780643799323.results',)`

Which looks to be the **repr** of the replica tuple.  It would be much more convenient if it were a list of newline separated URLs, so that it could be piped into other unix commands.

**Comment by pooya** [comment]
This issue had been resolved by 12d7ef9a0553f3952765b99d02fe796acfbcbd5a
