### ISSUE TITLE
Feature: Improve web based status console UI

### ISSUE THREAD

**Issue by trein** [discoproject/disco#470]
Hi,

I was wondering if you guys would be interested in adding [Bootstrap](http://getbootstrap.com/) for `Disco's` web based status console. I could try to work on this if you think it is pertinent.

Cheers,

**Comment by pooya** [comment]
@trein That would be wonderful.  It was one of the GSoC ideas: https://github.com/beamcommunity/beamcommunity.github.com/wiki/Project:-Disco

**Comment by trein** [comment]
Excellent. I will try to work on a prototype and as soon as I have something concrete, I show you guys.

**Comment by pooya** [comment]
@trein Thanks.
Please let us know if you have any questions.

I am closing this issue.
