### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by siedentop** [discoproject/disco#473]
# How to reproduce the error.

Follow the [installation tutorial](http://disco.readthedocs.org/en/latest/start/install.html), especially these lines:

```
git clone git://github.com/discoproject/disco.git DISCO_HOME
cd DISCO_HOME
make
bin/disco nodaemon
```

Verify that the web config page can be opened on http://localhost:8989/ .

Run the example as given in the tutorial:

```
python examples/util/count_words.py
```
# Actual Result

```
$ python examples/util/count_words.py 
Traceback (most recent call last):
  File "examples/util/count_words.py", line 1, in <module>
    from disco.core import Job, result_iterator
ImportError: No module named disco.core
```
# Expected Result

This is either a
- an error on my system or from me, OR
- some information is missing in the tutorial, OR
- a bug.

I would like to see the documentation changed to inform the novice user to what the `PYTHONPATH` has to be set, or what else needs to be done to make this work.
# System information
- This is on Debian 7 wheezy, Kernel: 3.2.54-2.
- Erlang installed from: http://www.erlang.org/download/otp_src_R16B03-1.tar.gz to my `$HOME` (but no errors on make).
- I do not have root access.
- Python 2.7.3 and Python 3.2.3
- Disco version: 3c1bb8bd4abbc4ddbfd3885fd43c4080a0299d19 and the latest stable release 0.5

**Comment by pooya** [comment]
@unapiedra This seems like an issue in the documentation.  You have to install disco before using it.
$ sudo make install
If you do not have root access, then you can install the python library for the user:
$ cd lib && python setup.py install --user

**Comment by pooya** [comment]
The documentation has been updated in the develop branch.
