### ISSUE TITLE
debian package generated from current develop branch doesn't install

### ISSUE THREAD

**Issue by gijzelaerr** [discoproject/disco#479]
```
$ sudo dpkg -i disco-node_0.5_amd64.deb
(Reading database ... 471784 files and directories currently installed.)
Preparing to replace disco-node 0.5 (using disco-node_0.5_amd64.deb) ...
Unpacking replacement disco-node ...
Setting up disco-node (0.5) ...
dpkg: error processing disco-node (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 disco-node
```

**Comment by pooya** [comment]
@gijzelaerr I had tested this at the time I created it.  Have you installed the dependencies?  Is there anyway we can get a better error message?

**Comment by gijzelaerr** [comment]
yes.

by running:

```
sudo sh -x /var/lib/dpkg/info/disco-node.postinst configure
```

but it fails silently. after removing the `--quiet` and `2>/dev/null` I get:

```
+ set -e
+ getent group
+ grep -q ^disco:
+ getent passwd
+ grep -q ^disco:
+ adduser --system --group --disabled-password --shell /bin/bash --home --no-create-home disco
adduser: The home dir must be an absolute path.
```

Build system is Ubuntu 12.04 btw.

**Comment by pooya** [comment]
Would you retry with commit bd94c6de5978771afa61f2ff9d286d50e7688f97 ? Thanks.

**Comment by gijzelaerr** [comment]
same problem.

**Comment by pooya** [comment]
@gijzelaerr OK. Thanks. I'll work on this as soon as I get a deb-based system.

**Comment by pmundkur** [comment]
It's possible I broke this in https://github.com/discoproject/disco/commit/2320492bf7c70c39a345fa671af9fcc6072fcf3a

**Comment by pooya** [comment]
@pmundkur Thanks.  That has been fixed already!
@gijzelaerr I could reproduce this issue on Ubuntu 13.10 but it was fixed with the aforementioned commit.  You should manually remove the files created by make debian and try again (or try it in a clean directory).
Thanks!

**Comment by gijzelaerr** [comment]
yep, package is building now!
