### ISSUE TITLE
debian package content should be in /usr, not /usr/local

### ISSUE THREAD

**Issue by gijzelaerr** [discoproject/disco#486]
The package violates the `file-in-usr-local` `dir-in-usr-local` debian policies. The files should be installed in `/usr`, not `/usr/local`. `/usr/local` is reserved for manually installed files.

http://lintian.debian.org/tags/file-in-usr-local.html

http://lintian.debian.org/tags/dir-in-usr-local.html

**Comment by pooya** [comment]
This suggestion is employed with 72ea146c29560d8c00cbeb5a0c9b371c065b656e.
