### ISSUE TITLE
support ddfs push from stdin

### ISSUE THREAD

**Issue by gijzelaerr** [discoproject/disco#489]
I'm trying to upload a directory to ddfs, which is not possible. As a work around I can tar the data. It would be nice if it is not required to store the intermediate result, for example by accepting a `ddfs push` from stdin.

for example:

 `$ tar -cO <directory> | ddfs push <label>`

the other way around works:

 `$ ddfs cat  <label> | tar xvp`

**Comment by rcarmo** [comment]
+1 for this. I'm now trying to upload a file to DDFS from a master node that has, alas, not enough storage to handle it in an uncompressed fashion, and being able to pipe things to `ddfs chunk` remotely would make that possible.

**Comment by pooya** [comment]
@gijzelaerr the ddfs push command has the -x (--tarball) option that lets you specify a tar file (ddfs chunk does not have that option).
It is not suitable for @rcarmo 's situation though because it uncompresses the tar file.

**Comment by rcarmo** [comment]
Actually, I'm not even using a tar file (straight up .csv.gz), but yeah, you're right. :)

**Comment by pooya** [comment]
Commit f7bdd7b7fd98a33419f4fc5630b4464342f807f6 should resolve this issue.

**Comment by rcarmo** [comment]
Thanks! I'll check out tip and give it a go over next week.

**Comment by rcarmo** [comment]
Hello there. I tried a fresh checkout, and both ddfs push and ddfs chunk seem to have trouble with parsing "-". Chunk complains that the "-" tag is not found, and push just pushes an empty file.

The command line I'm using is `zcat dataset.gz | ddfs chunk data:dataset -` and I'm getting:

`Unable to access resource (http://master:8989/ddfs/tag/-): Tag not found. (404)`

**Comment by pooya** [comment]
@rcarmo Please also update the python library (go to the lib directory and python setup.py install). This option only works for chunk (not push). You should see a help message about it when you issue:
  ddfs chunk --help
Thanks

**Comment by rcarmo** [comment]
I did a full make install and there was nothing in ddfs chunk --help (checked that before posting), but will check again.

**Comment by pooya** [comment]
@rcarmo There is a bug in Disco's installation process that does not re-build the python packages.

**Comment by rcarmo** [comment]
Quite so. I've since noticed that even after reinstalling, the Web UI still says it's version `Disco 0.5.1-76-gb5eef0c`.

I've tried uninstalling and reinstalling, and it's still presenting the same version number, so I'm going to take a more drastic approach...

**Comment by pooya** [comment]
@rcarmo That might be because we have changed disco to be installed in /usr/ instead of /usr/local. You have to go back to the old version. Uninstall it and then come to the new version and install the new one. Sorry for the inconvenience but we had to do it some time

**Comment by rcarmo** [comment]
Fixed the install problems and `ddfs chunk` now takes input from stdin, but it appears to have a memory leak -- I'm watching a very large import and the RAM taken is mounting steadily. Will report later.
