### ISSUE TITLE
disco-worker IO exception handling fails

### ISSUE THREAD

**Issue by efredine** [discoproject/disco#49]
disco-worker catches exceptions with the following code:
        try:
                run(method, mode, part, m)
        except comm.CommException, x:
                util.data_err("HTTP error: %s" % x)
        except IOError, x:
                util.data_err("IO error: %s" % x)

The calls to util.data_err fail because it requires 2 parameters.

**Comment by tuulos** [comment]
Thanks for reporting this. A fix will be pushed soon.
