### ISSUE TITLE
Static variables detected as modules 

### ISSUE THREAD

**Issue by trein** [discoproject/disco#508]
Hi,

I've implemented a simple MapReduce job using base class `Job`, but when I try to execute it I get the error:

```
  File "/Users/trein/Development/tools/disco/lib/disco/job.py", line 147, in run
    self.worker.jobhome(self, **jobargs),
  File "/Users/trein/Development/tools/disco/lib/disco/worker/__init__.py", line 209, in jobhome
    jobzip = self.jobzip(job, **jobargs)
  File "/Users/trein/Development/tools/disco/lib/disco/worker/classic/worker.py", line 310, in jobzip
    jobzip = super(Worker, self).jobzip(job, **jobargs)
  File "/Users/trein/Development/tools/disco/lib/disco/worker/__init__.py", line 242, in jobzip
    self['required_modules'] = self.get_modules(job, **jobargs)
  File "/Users/trein/Development/tools/disco/lib/disco/worker/__init__.py", line 170, in get_modules
    exclude=['Task'])
  File "/Users/trein/Development/tools/disco/lib/disco/worker/modutil.py", line 253, in find_modules
    raise ModUtilImportError(e, function)
disco.worker.modutil.ModUtilImportError: No module named CONSTANT: Could not find module defined in map. Maybe it is a typo. See documentation of the required_modules parameter for details on how to include modules.
```

I've tested my code on v0.4.5 and v0.5.1, and both versions presented the problem. Debugging the code, I noticed that [`modutil.scanner()`](https://github.com/discoproject/disco/blob/0.4.5/lib/disco/worker/classic/modutil.py#L126) is considering `CONSTANT` as a module because of the call `CONSTANT.get(a_key)` (please, correct me if I'm wrong).

Here is sample code that can be used to reproduce the problem.

``` python
from disco.core import Job
from disco.core import result_iterator


CONSTANT = {
    'key1': 'value1',
    'key2': 'value2',
    'key3': 'value3',
    'key4': 'value4',
}

class WordCount(Job):
    @staticmethod
    def map(line, params):
        for word in line.split():
            key_par = CONSTANT.get('key1', 'default_value')
            yield word, 1

    @staticmethod
    def reduce(iterator, params):
        from disco.util import kvgroup

        for word, counts in kvgroup(sorted(iterator)):
            yield word, sum(counts)

    def inputs(self):
        return ["http://discoproject.org/media/text/chekhov.txt"]

    def outputs(self):
        for word, count in result_iterator(self.wait(show=True)):
            print(word, count)

    def execute(self):
        self.run(input=self.inputs())
        self.outputs()


if __name__ == '__main__':
    from issue_sample_job import WordCount

    name = 'sample_trein_count'
    WordCount(name).execute()
```

For now, as a workaround, I'm accessing the dictionary directly by `CONSTANT['key1']`.

**Comment by pooya** [comment]
@trein The map and reduce functions cannot access the global variables of the file.  This is the same reason we add this line:
    from issue_sample_job import WordCount
If you want to use the global variable you have to import it before using it:
    from issue_sample_job import CONSTANT

Or you can pass it as parameter to the job.  See the datamining/kclustering.py for an example.

**Comment by trein** [comment]
@pooya Thanks for the heads-up :). I couldn't find anything about it on [docs](http://disco.readthedocs.org/en/develop/). Do you thing it would be a good idea to add more details about Disco's implementation there (like an advanced section perhaps)? I would like to collaborate and do it myself, but I think this task requires a deeper knowledge on Disco than I do so far.

**Comment by pooya** [comment]
@trein Right now the inline comments in the source code are the only source of such implementation details.
I am closing this issue.  Please re-open if you think further actions are necessary.
