### ISSUE TITLE
inet:gethostbyname() fails on some platforms

### ISSUE THREAD

**Issue by ahankinson** [discoproject/disco#51]
On FreeBSD 7.2, the inet:gethostname() call returns the short hostname without the domain, e.g., "example" instead of "example.com." This causes the master node to fail with the error:

<pre>
Error{EXIT,{{badmatch,{error,nxdomain}},[{handle_job,gethostname,0},{handle_job,set_disco_url,2},{handle_ctrl,handle,2},{scgi_server,handle_request,2},{scgi_server,scgi_worker,1}]}}
</pre>

The solution is to patch handle_job.erl to account for incomplete hostnames and append the domain when it isn't present.

<pre>
--- master/src/handle_job.erl.orig  2009-12-05 22:09:09.811589122 -0500
+++ master/src/handle_job.erl   2009-12-05 21:54:09.920556045 -0500
@@ -114,10 +114,14 @@
         end.
 
 gethostname() ->
-        {ok, Hostname} = inet:gethostname(),
-        {ok, Hostent}  = inet:gethostbyname(Hostname),
+        {ok, Host} = inet:gethostname(),
+        case inet_db:res_option(domain) of
+             "" -> Hostname = Host; 
+             Domain -> Hostname = Host ++ "." ++ Domain
+        end,
+        {ok, Hostent}  = inet:gethostbyname(Hostname),
         Hostent#hostent.h_name.
-        
+
 set_disco_url(undefined, Msg) ->
         {value, {_, SPort}} =
                 lists:keysearch(<<"SERVER_PORT">>, 1, Msg),
</pre>

This code was taken from http://web.mit.edu/erlang_vR11B-5/arch/i386_linux26/lib/erlang/lib/kernel-2.11.5/src/net_adm.erl

**Comment by tuulos** [comment]
gethostname() is not needed in 0.3 anymore which closes the bug
