### ISSUE TITLE
"bin/disco nodaemon" fails on mac 10.10 (yosemite dp7)

### ISSUE THREAD

**Issue by kd0g** [discoproject/disco#580]
from yosemite, "/usr/libexec/StartupItemContext" removed.

if i do "sudo ln -s /bin/bash /usr/libexec/StartupItemContext",
disco master starts, but slave don't.

**Comment by pooya** [comment]
Thanks for reporting this. I will try to figure out what's happening as soon as I get a chance to work with this version of OSX.

**Comment by pooya** [comment]
Please re-open if there is still some failures.
