### ISSUE TITLE
ddfs ls glob instead of prefix

### ISSUE THREAD

**Issue by erikdubbelboer** [discoproject/disco#599]
It would be nice if the [ddfs ls](https://github.com/discoproject/disco/blob/develop/bin/ddfscli.py#L275) command didn't just work with prefixes but whole glob patterns.

One options would be a command line flag to indicate whether the prefix argument is a prefix or a glob pattern. A better option would be to always append a \* to the end of prefix (if there isn't already one) so the command is backwards compatible and no command line flag is required.

I have already implemented this in python using [glob](https://docs.python.org/2/library/glob.html). But this requires to fetch all tags with a prefix of everything up to the first wildcard (*) and then filtering them using [glob](https://docs.python.org/2/library/glob.html). It would be much faster if this filtering was done in erlang.

I have no experience at all with erlang so I'm afraid I can't make a pull request myself.

**Comment by pooya** [comment]
ddfs_util:startswith function is responsible for this operation. This function accepts two binaries and should be very fast. listing tags with a specific prefix should be fast, so we have to be careful not to introduce a noticeable performance regressions.

**Comment by erikdubbelboer** [comment]
I'm unfamiliar with erlang so I'm afraid I can't fix it myself. Doesn't erlang have a library function comparable to https://docs.python.org/2/library/fnmatch.html ?

**Comment by pooya** [comment]
I couldn't find any good glob implementation in Erlang. Of course it has first and second level pattern matching but that's an overkill for this.

**Comment by erikdubbelboer** [comment]
I have been thinking about our use case and I have decided to do thing differently. I think I was trying to use the ddfs tagging system too much like an index instead of just tags. We now keep data about the tags in a separate database and use that to quickly query which tags we should request.

**Comment by pooya** [comment]
@ErikDubbelboer You might also want to take a look at the tag attributes in ddfs. They try to mimic the behavior of UNIX file attributes and keep meta-data about the files. Although, you still have to query them from Disco.

**Comment by erikdubbelboer** [comment]
I looked into it but it's not suitable for the things we want to do.

We store data in hourly increments and sometimes we need to map all tags for a certain time range. Things like UNIX file attributes are also not suitable for this.
