### ISSUE TITLE
dynamic partitions

### ISSUE THREAD

**Issue by jflatow** [discoproject/disco#61]
maps should be able to open/write to partitions dynamically (s.t. the number does not need to be predetermined)

**Comment by jflatow** [comment]
from #146:

1) a dynamic partition function that observer the key distribution on the fly, and spreads data accordingly

or 2) a system to first check the data distribution and then produce a good partition function accordingly

most often you just want equal keys to the same partition - system could optimize everything else behind the scenes

both 1) and 2) could warn you about an unbalanced distribution so you wouldn't have to wait until reduce to see that it's going to take ages

**Comment by pooya** [comment]
This issue has been fixed by the introduction of labels. There is no automatic checks available for the size of these labels though.
