### ISSUE TITLE
Adding Nodes (automated)

### ISSUE THREAD

**Issue by BitResolution** [discoproject/disco#623]
Hi we're deploying Disco using docker/ansible and would like to be able to add nodes without having to manually poke the UI. 

Is there an existing method (other than CURLing) to do this? E.g a config file or REST API?

Thanks

**Comment by pooya** [comment]
This is not the best solution, but you can always override the DISCO_MASTER_CONFIG file manually before starting disco. Disco will read that file and load the nodes from it.
On my desktop DISCO_MASTER_CONFIG is /usr/var/disco/disco_8989.config

If you have Erlang shell on disco, you can get the name of the file with: 
disco:get_setting("DISCO_MASTER_CONFIG").

**Comment by BitResolution** [comment]
Thanks works perfectly :)
