### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by BitResolution** [discoproject/disco#627]
Hi,

On your project homepage there is a link that say "Try Disco (alpha)" does this mean Disco should be considered alpha or that the "Try Disco" feature is in alpha?

Thanks
James

**Comment by pooya** [comment]
The "Try" Feature is alpha (as is the Sandstorm platform that Disco Demo runs in).

**Comment by BitResolution** [comment]
Great thanks for the clarification, our legal guys were getting a bit fussy/paranoid
