### ISSUE TITLE
How to let disco generate input data in real-time and then do map-reduce?

### ISSUE THREAD

**Issue by Kiddinglife** [discoproject/disco#639]
my input data has to be generated in real time instead of reading from the prepared text files.
I there a way to let mapper process load my python module and then run it to generate raw inputs and then do map-reduce on them?

**Comment by Kiddinglife** [comment]
I knew Yarn but it still separates real time raw input data generation from map-reduce? In other words, it does my job in two individual steps: 1. run my python module and generate raw inputs and store then in text files 2. use these text files in map-reduce-cluster.

**Comment by erikdubbelboer** [comment]
In theory you could run the map on empty blobs (as many as your module needs) and just `yield` the results of your module to the reduce function instead of anything from the file.

**Comment by Kiddinglife** [comment]
thanks. it seems work on me.
