### ISSUE TITLE
#!/usr/bin/env python instead of #!/usr/bin/python 

### ISSUE THREAD

**Issue by tuulos** [discoproject/disco#8]
A few scripts use #!/usr/bin/python (i.e. disco-worker) instead of #!/usr/bin/env python. When the scripts are executed directly, non-system python installations cannot be used.

**Comment by tuulos** [comment]
Does /usr/bin/env work on OS X? If someone can approve that it works on macs, I can make the change.

**Comment by jflatow** [comment]
Yes, I can attest to that (at least as of 10.5.6).

**Comment by tuulos** [comment]
Fixed in 0.2.3
