### ISSUE TITLE
disco.purge not working anymore in 0.2.4?

### ISSUE THREAD

**Issue by davin** [discoproject/disco#85]

**Comment by davin** [comment]
Calling purge doesn't do anything in the following script on my humble dual core lap-cluster.  Job 1 and 2 remain on status page.

<code>
from disco.core import Disco, result_iterator, Params
from disco.func import chain_reader, nop_reduce

def _mapDiag(e, params):
   if type(e) == tuple:
      e = e[0]
   output = []
   elems = e.split(";")
   for elem in elems:
      i, j, val = elem.split(",")
      if i == j:
         output.append(("%s,%s,%f" % (i,j,float(val)), ""))
   return output

disco = Disco("http://localhost:8989")
A = []
for i in range(0, 10):
        for j in range(0, 10):
         A.append("raw://%d,%d,%f" % (i,j, i*j))
myJob1 = disco.new_job(input=A, name="bug1", scheduler={"max_cores":2}, map=_mapDiag)
resDiag1 = myJob1.wait(clean=False)
myJob2 = disco.new_job(input=A, name="bug2", scheduler={"max_cores":2}, map=_mapDiag)
resDiag2 = myJob2.wait(clean=False)
myJob3 = disco.new_job(input=resDiag1+resDiag2, name="bug3", nr_reduces=2, map_reader=chain_reader, reduce=nop_reduce)
resDiag3 = myJob3.wait(clean=False)
disco.purge(myJob1)
disco.purge(myJob2)
</code>

**Comment by jflatow** [comment]
disco.purge(...) takes a job name, not a job instance, use either job.purge() or disco.purge(job.name)
