### ISSUE TITLE
clean=True raises JobError when launching job (disco 0.2.4)

### ISSUE THREAD

**Issue by jseppanen** [discoproject/disco#87]
when calling Disco(master).new_job(..., clean=True) in disco 0.2.4 I get the following error:

disco.error.JobError: Job http://discomaster:8989/filter@4f1:c3cab:8373a failed: Job status unknown job

the script used to work in disco 0.2.3; a simple workaround for 0.2.4 seems to be to set clean=False

**Comment by tuulos** [comment]
works with 0.3
