### ISSUE TITLE
DISCO_EVENTS=1 hangs in v0.2.4

### ISSUE THREAD

**Issue by davin** [discoproject/disco#88]
Running a disco job with command "DISCO_EVENTS=1 python bug.py" on my dual core cluster  returns "diag@4f1:c5ad7:4d561:" and hangs.  Running w/o "DISCO_EVENTS=1", however, the job terminates successfully.

**Comment by jflatow** [comment]
could you post bug.py (or perhaps use gist and link)?

**Comment by davin** [comment]
I suspect this might have to do with my lap-cluster network setup since the problem only occurs when I run the script at home but not at work.  It could also very well be that my machine is rigged by the IT dept at work. :)  Perhaps we should close this bug for now.

**Comment by davin** [comment]
I should also mention that it doesn't hang but just runs VERY slowly.  For example, if I run a job w/o DISCO_EVENTS=1, it finishes in a few seconds.  With DISCO_EVENTS=1, it takes several minutes.

**Comment by jflatow** [comment]
Sounds like this is not a bug in disco but due to slow network.
