### ISSUE TITLE
Running jobs with empty input gives "Jobs status dead" in v0.2.4

### ISSUE THREAD

**Issue by davin** [discoproject/disco#92]
I think it used to be that the job returns w/o error in previous version.

<code>
from disco.core import Disco
disco = Disco("http://localhost:8989")
def _map(e, params):
    return []
res = disco.new_job(input=[], name="bug", map=_map).wait()
</code>

**Comment by davin** [comment]
how do I format python code in posting?

**Comment by jflatow** [comment]
davin, what error do you get? I copied and pasted this on my local machine and it ran successfully

**Comment by davin** [comment]
I just ran this code again on my lapcluster and it gave me "job status dead".  On the status page,  all I see are:

2010/03/05 19:42:51master
Map phase
2010/03/05 19:42:51master
Starting job

The stack trace is:
Traceback (most recent call last):
  File "foo.py", line 5, in <module>
    res = disco.new_job(input=[], name="bug", map=_map).wait()
  File "/home/disco/disco/pydisco/disco/core.py", line 170, in wait
    return self.check_results(name, start_time, poll_interval \* 1000)
  File "/home/disco/disco/pydisco/disco/core.py", line 159, in check_results
    raise JobError("Job status %s" % status, self.host, name)
disco.error.JobError: Job http://localhost:8989/bug@4f3:c6016:94481 failed: Job status dead

**Comment by davin** [comment]
And here's what events look like in /srv/disco/data/_disco_4444/3d/bug@4f3:c60b8:13319

["2010/03/05 19:46:32","master","New job initialized!"]
["2010/03/05 19:46:32","master","Starting job"]
["2010/03/05 19:46:32","master","Map phase"]
