### ISSUE TITLE
Duplicate array-key error when I start up the master

### ISSUE THREAD

**Issue by xiufengliu** [discoproject/disco#95]
Hi,  I have downloaded disco 0.2.4, but i cannot start up master as it complains "Duplicate array-key". But on this same serve, disco 0.2.3 has been running very fine. So, what is the problem for disco 0.2.4? please investigate it. Thanks!
###### 

xiliu@h54:~/disco-0.2.4> make
erlc -W -o master/ebin master/src/disco_config.erl
erlc -W -o master/ebin master/src/disco.erl
erlc -W -o master/ebin master/src/disco_main.erl
erlc -W -o master/ebin master/src/disco_server.erl
erlc -W -o master/ebin master/src/disco_worker.erl
erlc -W -o master/ebin master/src/event_server.erl
master/src/event_server.erl:150: Warning: regexp:gsub/3: the regexp module is deprecated (will be removed in R15A); use the re module instead
erlc -W -o master/ebin master/src/event_stream.erl
erlc -W -o master/ebin master/src/fair_scheduler.erl
erlc -W -o master/ebin master/src/fair_scheduler_fair_policy.erl
erlc -W -o master/ebin master/src/fair_scheduler_fifo_policy.erl
erlc -W -o master/ebin master/src/fair_scheduler_job.erl
erlc -W -o master/ebin master/src/garbage_collect.erl
erlc -W -o master/ebin master/src/handle_ctrl.erl
erlc -W -o master/ebin master/src/handle_job.erl
erlc -W -o master/ebin master/src/job_queue.erl
erlc -W -o master/ebin master/src/json.erl
erlc -W -o master/ebin master/src/message_buffer.erl
erlc -W -o master/ebin master/src/netstring.erl
erlc -W -o master/ebin master/src/oob_server.erl
erlc -W -o master/ebin master/src/scgi.erl
erlc -W -o master/ebin master/src/scgi_server.erl
erlc -W -o master/ebin master/src/trunc_io.erl
master/src/trunc_io.erl:50: Warning: list/1 obsolete
master/src/trunc_io.erl:56: Warning: tuple/1 obsolete
master/src/trunc_io.erl:65: Warning: atom/1 obsolete
master/src/trunc_io.erl:72: Warning: binary/1 obsolete
master/src/trunc_io.erl:77: Warning: float/1 obsolete
master/src/trunc_io.erl:81: Warning: function/1 obsolete
master/src/trunc_io.erl:85: Warning: integer/1 obsolete
master/src/trunc_io.erl:89: Warning: pid/1 obsolete
master/src/trunc_io.erl:93: Warning: reference/1 obsolete
master/src/trunc_io.erl:97: Warning: port/1 obsolete
master/src/trunc_io.erl:101: Warning: list/1 obsolete
cp conf/settings.py.template conf/settings.py
xiliu@h54:~/disco-0.2.4> ls

xiliu@h54:~/disco-0.2.4/bin> ls
disco  disco.py
xiliu@h54:~/disco-0.2.4/bin> ./disco master nodaemon
Duplicate array-key: /disco/node/aobi/
2010-02-13 00:15:44: (configfile.c.907) source: $DISCO_MASTER_HOME/make-lighttpd-proxyconf.py line: 5 pos: 1 parser failed somehow near here: (COMMA) 
2010-02-13 00:15:44: (configfile.c.907) source: /home/xiliu/disco-0.2.4/conf/lighttpd-master.conf line: 53 pos: 1 parser failed somehow near here: (EOL) 
Failed to start lighttpd -f /home/xiliu/disco-0.2.4/conf/lighttpd-master.conf

xiliu@h54:~/disco-0.2.4/bin> ./disco -p
ACLOCAL_FLAGS = -I /opt/gnome/share/aclocal
COLORTERM = 1
CPU = x86_64
CSHEDIT = emacs
CVS_RSH = ssh
DISCO_CONFIG = /home/xiliu/disco-0.2.4/root/disco_4444.config
DISCO_DATA = /home/xiliu/disco-0.2.4/root/data
DISCO_DEBUG = off
DISCO_ERLANG = erl
DISCO_EVENTS = 
DISCO_FLAGS = 
DISCO_HTTPD = lighttpd
DISCO_LOCAL_DIR = /home/xiliu/disco-0.2.4/root/local/_disco_4444
DISCO_LOG_DIR = /home/xiliu/disco-0.2.4/log
DISCO_MASTER_HOME = /home/xiliu/disco-0.2.4/master
DISCO_MASTER_HOST = h54
DISCO_MASTER_ROOT = /home/xiliu/disco-0.2.4/root/data/_disco_4444
DISCO_NAME = disco_4444
DISCO_PID_DIR = /home/xiliu/disco-0.2.4/run
DISCO_PORT = 8989
DISCO_PROXY = 
DISCO_ROOT = /home/xiliu/disco-0.2.4/root
DISCO_SCGI_PORT = 4444
DISCO_SCHEDULER = fair
DISCO_SCHEDULER_ALPHA = 0.001
DISCO_TEST_HOST = h54
DISCO_TEST_PORT = 9444
DISCO_TEST_PURGE = purge
DISCO_ULIMIT = 16000000
DISCO_USER = xiliu
DISCO_WORKER = /home/xiliu/disco-0.2.4/node/disco-worker
DISCO_WWW_ROOT = /home/xiliu/disco-0.2.4/master/www
ENV = /etc/bash.bashrc
FROM_HEADER = 
GNOME2_PATH = /usr/local:/opt/gnome:/usr
GROFF_NO_SGR = yes
GTK_PATH = /usr/local/lib/gtk-2.0:/opt/gnome/lib/gtk-2.0:/usr/lib/gtk-2.0
GTK_PATH64 = /usr/local/lib64/gtk-2.0:/opt/gnome/lib64/gtk-2.0:/usr/lib64/gtk-2.0
G_BROKEN_FILENAMES = 1
G_FILENAME_ENCODING = @locale,UTF-8,ISO-8859-15,CP1252
HISTSIZE = 1000
HOME = /home/xiliu
HOST = h54
HOSTNAME = h54
HOSTTYPE = x86_64
INFODIR = /usr/local/info:/usr/share/info:/usr/info
INFOPATH = /usr/local/info:/usr/share/info:/usr/info:/opt/gnome/share/info
INPUTRC = /home/xiliu/.inputrc
JAVA_BINDIR = /usr/lib64/jvm/java/bin
JAVA_HOME = /usr/lib64/jvm/java
JAVA_ROOT = /usr/lib64/jvm/java
JDK_HOME = /usr/lib64/jvm/java
JRE_HOME = /usr/lib64/jvm/java/jre
LANG = en_US.UTF-8
LESS = -M -I
LESSCLOSE = lessclose.sh %s %s
LESSKEY = /etc/lesskey.bin
LESSOPEN = lessopen.sh %s
LESS_ADVANCED_PREPROCESSOR = no
LOGNAME = xiliu
LS_COLORS = no=00:fi=00:di=01;34:ln=00;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:_.cmd=00;32:_.exe=01;32:_.com=01;32:_.bat=01;32:_.btm=01;32:_.dll=01;32:_.tar=00;31:_.tbz=00;31:_.tgz=00;31:_.rpm=00;31:_.deb=00;31:_.arj=00;31:_.taz=00;31:_.lzh=00;31:_.zip=00;31:_.zoo=00;31:_.z=00;31:_.Z=00;31:_.gz=00;31:_.bz2=00;31:_.tb2=00;31:_.tz2=00;31:_.tbz2=00;31:_.avi=01;35:_.bmp=01;35:_.fli=01;35:_.gif=01;35:_.jpg=01;35:_.jpeg=01;35:_.mng=01;35:_.mov=01;35:_.mpg=01;35:_.pcx=01;35:_.pbm=01;35:_.pgm=01;35:_.png=01;35:_.ppm=01;35:_.tga=01;35:_.tif=01;35:_.xbm=01;35:_.xpm=01;35:_.dl=01;35:_.gl=01;35:_.wmv=01;35:_.aiff=00;32:_.au=00;32:_.mid=00;32:_.mp3=00;32:_.ogg=00;32:_.voc=00;32:*.wav=00;32:
LS_OPTIONS = -N --color=tty -T 0
MACHTYPE = x86_64-suse-linux
MAIL = /var/mail/xiliu
MANPATH = /usr/local/man:/usr/local/share/man:/usr/share/man:/usr/X11R6/man:/opt/gnome/share/man:/usr/local/pgsql/man/
MINICOM = -c on
MORE = -sl
NNTPSERVER = news
OLDPWD = /home/xiliu/disco-0.2.4
OSTYPE = linux
PAGER = less
PATH = /home/xiliu/bin:/usr/local/bin:/usr/bin:/usr/X11R6/bin:/bin:/usr/games:/opt/gnome/bin:/opt/kde3/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/usr/local/pgsql/bin/:/home/xiliu/sbin:/home/xiliu/bin
PKG_CONFIG_PATH = /usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig:/opt/kde3/lib64/pkgconfig:/opt/gnome/lib64/pkgconfig:/opt/gnome/lib64/pkgconfig:/opt/gnome/share/pkgconfig
PROFILEREAD = true
PWD = /home/xiliu/disco-0.2.4/bin
PYTHONPATH = /home/xiliu/workspace/etlonmapred/offline2:/home/xiliu/disco/pydisco:/home/xiliu/disco/node:/home/xiliu/disco/util
PYTHONSTARTUP = /etc/pythonstart
QT_SYSTEM_DIR = /usr/share/desktop-data
SDK_HOME = /usr/lib64/jvm/java
SHELL = /bin/bash
SHLVL = 1
SSH_CLIENT = 130.225.195.9 53715 22
SSH_CONNECTION = 130.225.195.9 53715 192.168.81.55 22
SSH_SENDS_LOCALE = yes
SSH_TTY = /dev/pts/1
TERM = xterm
TEXINPUTS = :/home/xiliu/.TeX:/usr/share/doc/.TeX:/usr/doc/.TeX
USER = xiliu
WINDOWMANAGER = /usr/X11R6/bin/gnome
XCURSOR_THEME = Industrial
XDG_CONFIG_DIRS = /usr/local/etc/xdg/:/etc/xdg/:/etc/opt/gnome/xdg/
XDG_DATA_DIRS = /usr/local/share/:/usr/share/:/etc/opt/kde3/share/:/opt/kde3/share/:/opt/gnome/share/
XKEYSYMDB = /usr/X11R6/lib/X11/XKeysymDB
XNLSPATH = /usr/X11R6/lib/X11/nls
_ = ./disco
mc = () {  . /usr/share/mc/bin/mc-wrapper.sh
}
xiliu@h54:~/disco-0.2.4/bin>

**Comment by jflatow** [comment]
do you have duplicates in your /etc/hosts? In 0.2.3 make-lighttpd-proxyconf would have only read the first entry on a line, it now reads aliases. If there are duplicates in the aliases lighttpd will complain when it tries to start up.

**Comment by xiufengliu** [comment]
Hi, jflatow: Following is my /etc/hosts, is the uplicate aliases you mentioned in the last line? but the last line the ip is 127.0.0.2, instead of 127.0.0.1

xiliu@h54:~> cat /etc/hosts
127.0.0.1       localhost

::1             localhost ipv6-localhost ipv6-loopback

fe00::0         ipv6-localnet

ff00::0         ipv6-mcastprefix
ff02::1         ipv6-allnodes
ff02::2         ipv6-allrouters
ff02::3         ipv6-allhosts
127.0.0.2       aobi aobi

**Comment by jflatow** [comment]
Yes, the last line is exactly the issue: not because it is similar to the first line but because you only need to specify 'aobi' once on that line (the rest of the names in the lines are aliases, so you have a duplicate).
