### ISSUE TITLE
job.wait() often raises timeout errors in 0.2.4

### ISSUE THREAD

**Issue by jseppanen** [discoproject/disco#96]
Often when a job is running and the python script is waiting for it to finish using job.wait() API call, disco 0.2.4 at some point raises a JobError("Timeout"). This has no effect on the actual job, which will continue to run and finish successfully, and can be seen in the web UI as usual. Here's one actual traceback that just occurred:

Traceback (most recent call last):
  File "filter.py", line 90, in <module>
    res=job.wait()
  File "/usr/lib/pymodules/python2.5/disco/core.py", line 170, in wait
    return self.check_results(name, start_time, poll_interval \* 1000)
  File "/usr/lib/pymodules/python2.5/disco/core.py", line 161, in check_results
    raise JobError("Timeout", self.host, name)
disco.error.JobError: Job http://discomaster:8989/filter@4f2:3798c:45c03 failed: Timeout

After the job has finished successfully, I am able to retrieve its results using Disco('disco://discomaster').results(...) manually.

**Comment by tuulos** [comment]
bugfix: timeouts were handled incorrectly in wait(). Closed by a8c402929021e48356b432cc53736bd0bb4983e2
