### ISSUE TITLE
Error handling and propagation in map and reduce tasks

### ISSUE THREAD

**Issue by davin** [discoproject/disco#99]
I have a map routine that throws an error whenever it encounters bad input data.  How do I escalate the error upward so that instead of the job crashing and returning a general error like "JobError: Job http://localhost:8989/myJob@4f2:623ee:e1b36 failed: Job status dead", it would show the actual root error which is more informative?

**Comment by pmundkur** [comment]
The actual error exception and trace_back should appear in 'disco events' and in the UI.  This has been the case for a long time; this bug should have been closed a while ago.
